# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: three-node.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='three-node.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10three-node.proto\"U\n\rSystemRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12\x1f\n\x17max_tokens_per_sentence\x18\x02 \x01(\x05\x12\x11\n\tnan_value\x18\x03 \x01(\x03\"\x9e\x02\n\x0eSystemResponse\x12\x19\n\x11original_sentence\x18\x01 \x01(\t\x12%\n\x06tokens\x18\x03 \x03(\x0b\x32\x15.SystemResponse.Token\x1a\xc9\x01\n\x05Token\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x11\n\tis_number\x18\x02 \x01(\x08\x12\r\n\x05value\x18\x03 \x01(\x03\x12*\n\x02\x65p\x18\x04 \x01(\x0b\x32\x1e.SystemResponse.Token.Endpoint\x12\r\n\x05label\x18\x05 \x01(\t\x1aU\n\x08\x45ndpoint\x12\x10\n\x08position\x18\x01 \x01(\x05\x12\x0e\n\x06length\x18\x02 \x01(\x05\x12\x13\n\x0bline_number\x18\x03 \x01(\x05\x12\x12\n\nline_start\x18\x04 \x01(\x05\"4\n\x0cSplitRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12\x12\n\nmax_tokens\x18\x02 \x01(\x05\"\x98\x01\n\rSplitResponse\x12$\n\x06tokens\x18\x01 \x03(\x0b\x32\x14.SplitResponse.Token\x1a\x61\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\x05\x12\x0e\n\x06length\x18\x03 \x01(\x05\x12\x13\n\x0bline_number\x18\x04 \x01(\x05\x12\x12\n\nline_start\x18\x05 \x01(\x05\"\x1c\n\x0cLabelRequest\x12\x0c\n\x04word\x18\x01 \x01(\t\"\x1e\n\rLabelResponse\x12\r\n\x05label\x18\x01 \x01(\t\"1\n\nToiRequest\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x15\n\rdefault_value\x18\x02 \x01(\x03\"3\n\x0bToiResponse\x12\x11\n\tnum_value\x18\x01 \x01(\x03\x12\x11\n\tis_number\x18\x02 \x01(\x08\x32\xbe\x01\n\x10ThreeNodeExample\x12-\n\x08tokenize\x12\x0e.SystemRequest\x1a\x0f.SystemResponse\"\x00\x12(\n\x05split\x12\r.SplitRequest\x1a\x0e.SplitResponse\"\x00\x12(\n\x05label\x12\r.LabelRequest\x1a\x0e.LabelResponse\"\x00\x12\'\n\x08strtoint\x12\x0b.ToiRequest\x1a\x0c.ToiResponse\"\x00\x62\x06proto3')
)




_SYSTEMREQUEST = _descriptor.Descriptor(
  name='SystemRequest',
  full_name='SystemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='SystemRequest.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_tokens_per_sentence', full_name='SystemRequest.max_tokens_per_sentence', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nan_value', full_name='SystemRequest.nan_value', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=105,
)


_SYSTEMRESPONSE_TOKEN_ENDPOINT = _descriptor.Descriptor(
  name='Endpoint',
  full_name='SystemResponse.Token.Endpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='SystemResponse.Token.Endpoint.position', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='SystemResponse.Token.Endpoint.length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='line_number', full_name='SystemResponse.Token.Endpoint.line_number', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='line_start', full_name='SystemResponse.Token.Endpoint.line_start', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=394,
)

_SYSTEMRESPONSE_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='SystemResponse.Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='SystemResponse.Token.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_number', full_name='SystemResponse.Token.is_number', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='SystemResponse.Token.value', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ep', full_name='SystemResponse.Token.ep', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='SystemResponse.Token.label', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SYSTEMRESPONSE_TOKEN_ENDPOINT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=394,
)

_SYSTEMRESPONSE = _descriptor.Descriptor(
  name='SystemResponse',
  full_name='SystemResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='original_sentence', full_name='SystemResponse.original_sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokens', full_name='SystemResponse.tokens', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SYSTEMRESPONSE_TOKEN, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=394,
)


_SPLITREQUEST = _descriptor.Descriptor(
  name='SplitRequest',
  full_name='SplitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='SplitRequest.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_tokens', full_name='SplitRequest.max_tokens', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=448,
)


_SPLITRESPONSE_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='SplitResponse.Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='SplitResponse.Token.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='SplitResponse.Token.position', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='SplitResponse.Token.length', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='line_number', full_name='SplitResponse.Token.line_number', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='line_start', full_name='SplitResponse.Token.line_start', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=603,
)

_SPLITRESPONSE = _descriptor.Descriptor(
  name='SplitResponse',
  full_name='SplitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tokens', full_name='SplitResponse.tokens', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SPLITRESPONSE_TOKEN, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=603,
)


_LABELREQUEST = _descriptor.Descriptor(
  name='LabelRequest',
  full_name='LabelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='LabelRequest.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=605,
  serialized_end=633,
)


_LABELRESPONSE = _descriptor.Descriptor(
  name='LabelResponse',
  full_name='LabelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='LabelResponse.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=635,
  serialized_end=665,
)


_TOIREQUEST = _descriptor.Descriptor(
  name='ToiRequest',
  full_name='ToiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='ToiRequest.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='default_value', full_name='ToiRequest.default_value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=667,
  serialized_end=716,
)


_TOIRESPONSE = _descriptor.Descriptor(
  name='ToiResponse',
  full_name='ToiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_value', full_name='ToiResponse.num_value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_number', full_name='ToiResponse.is_number', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=718,
  serialized_end=769,
)

_SYSTEMRESPONSE_TOKEN_ENDPOINT.containing_type = _SYSTEMRESPONSE_TOKEN
_SYSTEMRESPONSE_TOKEN.fields_by_name['ep'].message_type = _SYSTEMRESPONSE_TOKEN_ENDPOINT
_SYSTEMRESPONSE_TOKEN.containing_type = _SYSTEMRESPONSE
_SYSTEMRESPONSE.fields_by_name['tokens'].message_type = _SYSTEMRESPONSE_TOKEN
_SPLITRESPONSE_TOKEN.containing_type = _SPLITRESPONSE
_SPLITRESPONSE.fields_by_name['tokens'].message_type = _SPLITRESPONSE_TOKEN
DESCRIPTOR.message_types_by_name['SystemRequest'] = _SYSTEMREQUEST
DESCRIPTOR.message_types_by_name['SystemResponse'] = _SYSTEMRESPONSE
DESCRIPTOR.message_types_by_name['SplitRequest'] = _SPLITREQUEST
DESCRIPTOR.message_types_by_name['SplitResponse'] = _SPLITRESPONSE
DESCRIPTOR.message_types_by_name['LabelRequest'] = _LABELREQUEST
DESCRIPTOR.message_types_by_name['LabelResponse'] = _LABELRESPONSE
DESCRIPTOR.message_types_by_name['ToiRequest'] = _TOIREQUEST
DESCRIPTOR.message_types_by_name['ToiResponse'] = _TOIRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SystemRequest = _reflection.GeneratedProtocolMessageType('SystemRequest', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMREQUEST,
  __module__ = 'three_node_pb2'
  # @@protoc_insertion_point(class_scope:SystemRequest)
  ))
_sym_db.RegisterMessage(SystemRequest)

SystemResponse = _reflection.GeneratedProtocolMessageType('SystemResponse', (_message.Message,), dict(

  Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), dict(

    Endpoint = _reflection.GeneratedProtocolMessageType('Endpoint', (_message.Message,), dict(
      DESCRIPTOR = _SYSTEMRESPONSE_TOKEN_ENDPOINT,
      __module__ = 'three_node_pb2'
      # @@protoc_insertion_point(class_scope:SystemResponse.Token.Endpoint)
      ))
    ,
    DESCRIPTOR = _SYSTEMRESPONSE_TOKEN,
    __module__ = 'three_node_pb2'
    # @@protoc_insertion_point(class_scope:SystemResponse.Token)
    ))
  ,
  DESCRIPTOR = _SYSTEMRESPONSE,
  __module__ = 'three_node_pb2'
  # @@protoc_insertion_point(class_scope:SystemResponse)
  ))
_sym_db.RegisterMessage(SystemResponse)
_sym_db.RegisterMessage(SystemResponse.Token)
_sym_db.RegisterMessage(SystemResponse.Token.Endpoint)

SplitRequest = _reflection.GeneratedProtocolMessageType('SplitRequest', (_message.Message,), dict(
  DESCRIPTOR = _SPLITREQUEST,
  __module__ = 'three_node_pb2'
  # @@protoc_insertion_point(class_scope:SplitRequest)
  ))
_sym_db.RegisterMessage(SplitRequest)

SplitResponse = _reflection.GeneratedProtocolMessageType('SplitResponse', (_message.Message,), dict(

  Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), dict(
    DESCRIPTOR = _SPLITRESPONSE_TOKEN,
    __module__ = 'three_node_pb2'
    # @@protoc_insertion_point(class_scope:SplitResponse.Token)
    ))
  ,
  DESCRIPTOR = _SPLITRESPONSE,
  __module__ = 'three_node_pb2'
  # @@protoc_insertion_point(class_scope:SplitResponse)
  ))
_sym_db.RegisterMessage(SplitResponse)
_sym_db.RegisterMessage(SplitResponse.Token)

LabelRequest = _reflection.GeneratedProtocolMessageType('LabelRequest', (_message.Message,), dict(
  DESCRIPTOR = _LABELREQUEST,
  __module__ = 'three_node_pb2'
  # @@protoc_insertion_point(class_scope:LabelRequest)
  ))
_sym_db.RegisterMessage(LabelRequest)

LabelResponse = _reflection.GeneratedProtocolMessageType('LabelResponse', (_message.Message,), dict(
  DESCRIPTOR = _LABELRESPONSE,
  __module__ = 'three_node_pb2'
  # @@protoc_insertion_point(class_scope:LabelResponse)
  ))
_sym_db.RegisterMessage(LabelResponse)

ToiRequest = _reflection.GeneratedProtocolMessageType('ToiRequest', (_message.Message,), dict(
  DESCRIPTOR = _TOIREQUEST,
  __module__ = 'three_node_pb2'
  # @@protoc_insertion_point(class_scope:ToiRequest)
  ))
_sym_db.RegisterMessage(ToiRequest)

ToiResponse = _reflection.GeneratedProtocolMessageType('ToiResponse', (_message.Message,), dict(
  DESCRIPTOR = _TOIRESPONSE,
  __module__ = 'three_node_pb2'
  # @@protoc_insertion_point(class_scope:ToiResponse)
  ))
_sym_db.RegisterMessage(ToiResponse)



_THREENODEEXAMPLE = _descriptor.ServiceDescriptor(
  name='ThreeNodeExample',
  full_name='ThreeNodeExample',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=772,
  serialized_end=962,
  methods=[
  _descriptor.MethodDescriptor(
    name='tokenize',
    full_name='ThreeNodeExample.tokenize',
    index=0,
    containing_service=None,
    input_type=_SYSTEMREQUEST,
    output_type=_SYSTEMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='split',
    full_name='ThreeNodeExample.split',
    index=1,
    containing_service=None,
    input_type=_SPLITREQUEST,
    output_type=_SPLITRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='label',
    full_name='ThreeNodeExample.label',
    index=2,
    containing_service=None,
    input_type=_LABELREQUEST,
    output_type=_LABELRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='strtoint',
    full_name='ThreeNodeExample.strtoint',
    index=3,
    containing_service=None,
    input_type=_TOIREQUEST,
    output_type=_TOIRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_THREENODEEXAMPLE)

DESCRIPTOR.services_by_name['ThreeNodeExample'] = _THREENODEEXAMPLE

# @@protoc_insertion_point(module_scope)
