/* This file is automatically generated by Lemon from input grammar
** source file "flow-parser.y". */
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 28 "flow-parser.y"

#include <iostream>
#include "flow-ast.H"
#define YYNOERRORRECOVERY
#line 34 "flow-parser.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef FTK_ID
#define FTK_ID                              1
#define FTK_STRING                          2
#define FTK_INTEGER                         3
#define FTK_FLOAT                           4
#define FTK_SYMBOL                          5
#define FTK_NODE                            6
#define FTK_CONTAINER                       7
#define FTK_ENTRY                           8
#define FTK_IMPORT                          9
#define FTK_DEFINE                         10
#define FTK_OUTPUT                         11
#define FTK_RETURN                         12
#define FTK_ERROR                          13
#define FTK_ENDPOINT                       14
#define FTK_IMAGE                          15
#define FTK_MOUNT                          16
#define FTK_ENVIRONMENT                    17
#define FTK_INPUT                          18
#define FTK_SEMICOLON                      19
#define FTK_DOT                            20
#define FTK_AT                             21
#define FTK_COMMA                          22
#define FTK_EQUALS                         23
#define FTK_COLON                          24
#define FTK_QUESTION                       25
#define FTK_OR                             26
#define FTK_AND                            27
#define FTK_BAR                            28
#define FTK_CARET                          29
#define FTK_AMP                            30
#define FTK_NE                             31
#define FTK_EQ                             32
#define FTK_GT                             33
#define FTK_LT                             34
#define FTK_GE                             35
#define FTK_LE                             36
#define FTK_COMP                           37
#define FTK_SHR                            38
#define FTK_SHL                            39
#define FTK_PLUS                           40
#define FTK_MINUS                          41
#define FTK_STAR                           42
#define FTK_SLASH                          43
#define FTK_PERCENT                        44
#define FTK_BANG                           45
#define FTK_TILDA                          46
#define FTK_DOLLAR                         47
#define FTK_HASH                           48
#define FTK_UMINUS                         49
#define FTK_OPENPAR                        50
#define FTK_CLOSEPAR                       51
#define FTK_OPENBRA                        52
#define FTK_CLOSEBRA                       53
#define FTK_OPENSQB                        54
#define FTK_CLOSESQB                       55
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    flow_parserTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is flow_parserTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    flow_parserARG_SDECL     A static variable declaration for the %extra_argument
**    flow_parserARG_PDECL     A parameter declaration for the %extra_argument
**    flow_parserARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    flow_parserARG_STORE     Code to store %extra_argument into yypParser
**    flow_parserARG_FETCH     Code to extract %extra_argument from yypParser
**    flow_parserCTX_*         As flow_parserARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 79
#define YYACTIONTYPE unsigned short int
#define flow_parserTOKENTYPE int
typedef union {
  int yyinit;
  flow_parserTOKENTYPE yy0;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define flow_parserARG_SDECL  flow_ast *ast ;
#define flow_parserARG_PDECL , flow_ast *ast 
#define flow_parserARG_PARAM ,ast 
#define flow_parserARG_FETCH  flow_ast *ast =yypParser->ast ;
#define flow_parserARG_STORE yypParser->ast =ast ;
#define flow_parserCTX_SDECL
#define flow_parserCTX_PDECL
#define flow_parserCTX_PARAM
#define flow_parserCTX_FETCH
#define flow_parserCTX_STORE
#define YYNSTATE             103
#define YYNRULE              78
#define YYNRULE_WITH_ACTION  78
#define YYNTOKEN             56
#define YY_MAX_SHIFT         102
#define YY_MIN_SHIFTREDUCE   152
#define YY_MAX_SHIFTREDUCE   229
#define YY_ERROR_ACTION      230
#define YY_ACCEPT_ACTION     231
#define YY_NO_ACTION         232
#define YY_MIN_REDUCE        233
#define YY_MAX_REDUCE        310
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (736)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   279,   89,   52,  231,   46,   74,   80,  247,  101,   43,
 /*    10 */   269,   24,   24,  268,   72,  275,   26,  280,  269,   47,
 /*    20 */   285,  268,   47,   88,    3,    4,    5,    6,   32,   80,
 /*    30 */   246,   11,   12,    9,   10,    7,    8,   13,   25,   25,
 /*    40 */    20,   17,   15,   16,   14,   40,   15,   16,   14,   84,
 /*    50 */     4,    5,    6,   23,   41,   33,   11,   12,    9,   10,
 /*    60 */     7,    8,   13,  162,  161,   20,   17,   15,   16,   14,
 /*    70 */   186,  182,  183,   48,   69,  275,  200,    4,    5,    6,
 /*    80 */   182,  183,   22,   11,   12,    9,   10,    7,    8,   13,
 /*    90 */   160,  159,   20,   17,   15,   16,   14,   20,   17,   15,
 /*   100 */    16,   14,  193,   50,    4,    5,    6,  266,   39,   38,
 /*   110 */    11,   12,    9,   10,    7,    8,   13,   39,   38,   20,
 /*   120 */    17,   15,   16,   14,    6,  284,  265,   47,   11,   12,
 /*   130 */     9,   10,    7,    8,   13,   73,  275,   20,   17,   15,
 /*   140 */    16,   14,   83,  186,  182,  183,   11,   12,    9,   10,
 /*   150 */     7,    8,   13,  228,  229,   20,   17,   15,   16,   14,
 /*   160 */    42,  186,  182,  183,    9,   10,    7,    8,   13,  233,
 /*   170 */    26,   20,   17,   15,   16,   14,  226,  186,  182,  183,
 /*   180 */    76,   39,   38,  268,  238,  100,   18,   87,   35,   36,
 /*   190 */    88,   21,  201,   83,  186,  182,  183,  102,   77,   39,
 /*   200 */    38,  268,  226,   85,   18,   87,   35,   36,   44,   21,
 /*   210 */   276,   83,  186,  182,  183,   39,   38,  279,   89,   55,
 /*   220 */    34,   81,   93,  228,  229,  268,   82,  269,  228,  229,
 /*   230 */   268,   27,   39,   38,  280,   71,   47,   18,   87,   35,
 /*   240 */    36,  256,   21,   19,   49,  186,  182,  183,   48,   95,
 /*   250 */    39,   38,  268,   48,   33,   18,   87,   35,   36,  225,
 /*   260 */     1,  228,  229,  158,  174,  237,   31,   30,   49,  186,
 /*   270 */   182,  183,  202,  171,  170,   45,  169,  196,   75,  279,
 /*   280 */    89,   57,  190,   39,   38,  255,  192,   79,  191,  269,
 /*   290 */    29,   28,  268,   37,  225,   27,  280,   88,   47,  279,
 /*   300 */    89,   51,    2,   86,  227,  173,  172,   39,   38,  269,
 /*   310 */   252,   92,  268,  251,   94,  250,  280,   37,   47,   27,
 /*   320 */   279,   89,   58,   96,  249,  248,  155,  232,  232,  232,
 /*   330 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   340 */   279,   89,   59,  232,  232,  232,  232,  232,  232,  232,
 /*   350 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   360 */   279,   89,   62,  232,  232,  232,  232,  232,  232,  232,
 /*   370 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   380 */   279,   89,   63,  232,  232,  232,  232,  232,  232,  232,
 /*   390 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   400 */   279,   89,   64,  232,  232,  232,  232,  232,  232,  232,
 /*   410 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   420 */   279,   89,   65,  232,  232,  232,  232,  232,  232,  232,
 /*   430 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   440 */   279,   89,   60,  232,  232,  232,  232,  232,  232,  232,
 /*   450 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   460 */   279,   89,   61,  232,  232,  232,  232,  232,  232,  232,
 /*   470 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   480 */   279,   89,   66,  232,  232,  232,  232,  232,  232,  232,
 /*   490 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   500 */   279,   89,  291,  232,  232,  232,  232,  232,  232,  232,
 /*   510 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   520 */   279,   89,  290,  232,  232,  232,  232,  232,  232,  232,
 /*   530 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   540 */   279,   89,  289,  232,  232,  232,  232,  232,  232,  232,
 /*   550 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   560 */   279,   89,   68,  232,  232,  232,  232,  232,  232,  232,
 /*   570 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   580 */   279,   89,  286,  232,  232,  232,  232,  232,  232,  232,
 /*   590 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   600 */   279,   89,   56,  232,  232,  232,  232,  232,  232,  232,
 /*   610 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   620 */   279,   89,   67,  232,  232,  232,  232,  232,  232,  232,
 /*   630 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   640 */   279,   89,   52,  232,  232,  232,  232,  232,  232,  232,
 /*   650 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   660 */   279,   89,   54,  232,  232,  232,  232,  232,  232,  232,
 /*   670 */   269,  232,  232,  268,  232,  232,  232,  280,  232,   47,
 /*   680 */   279,   89,   53,  232,  232,  232,  232,  232,  232,  232,
 /*   690 */   269,  232,  232,  268,   70,  232,  232,  280,   99,   47,
 /*   700 */   232,  232,   98,   97,   91,   90,  268,  232,  232,  232,
 /*   710 */   232,   70,  232,  232,  232,  248,  232,  232,  232,  249,
 /*   720 */    78,   91,   90,  268,  232,  232,  232,  232,   13,  232,
 /*   730 */   232,   20,   17,   15,   16,   14,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    59,   60,   61,   56,   57,   58,   66,   67,   59,   60,
 /*    10 */    69,    1,    1,   72,   73,   74,    1,   76,   69,   78,
 /*    20 */    76,   72,   78,   20,   24,   25,   26,   27,   65,   66,
 /*    30 */    67,   31,   32,   33,   34,   35,   36,   37,    1,    1,
 /*    40 */    40,   41,   42,   43,   44,    1,   42,   43,   44,    1,
 /*    50 */    25,   26,   27,   50,    1,   52,   31,   32,   33,   34,
 /*    60 */    35,   36,   37,   53,   53,   40,   41,   42,   43,   44,
 /*    70 */     2,    3,    4,   22,   73,   74,   51,   25,   26,   27,
 /*    80 */     3,    4,   75,   31,   32,   33,   34,   35,   36,   37,
 /*    90 */    53,   53,   40,   41,   42,   43,   44,   40,   41,   42,
 /*   100 */    43,   44,   51,   51,   25,   26,   27,   72,   40,   41,
 /*   110 */    31,   32,   33,   34,   35,   36,   37,   40,   41,   40,
 /*   120 */    41,   42,   43,   44,   27,   76,   72,   78,   31,   32,
 /*   130 */    33,   34,   35,   36,   37,   73,   74,   40,   41,   42,
 /*   140 */    43,   44,    1,    2,    3,    4,   31,   32,   33,   34,
 /*   150 */    35,   36,   37,   23,   24,   40,   41,   42,   43,   44,
 /*   160 */     1,    2,    3,    4,   33,   34,   35,   36,   37,    0,
 /*   170 */     1,   40,   41,   42,   43,   44,    1,    2,    3,    4,
 /*   180 */    69,   40,   41,   72,   62,   66,   45,   46,   47,   48,
 /*   190 */    20,   50,   51,    1,    2,    3,    4,   58,   69,   40,
 /*   200 */    41,   72,    1,   60,   45,   46,   47,   48,    1,   50,
 /*   210 */    74,    1,    2,    3,    4,   40,   41,   59,   60,   61,
 /*   220 */    50,   21,   69,   23,   24,   72,   21,   69,   23,   24,
 /*   230 */    72,   52,   40,   41,   76,   77,   78,   45,   46,   47,
 /*   240 */    48,   64,   50,   22,    1,    2,    3,    4,   22,   69,
 /*   250 */    40,   41,   72,   22,   52,   45,   46,   47,   48,   21,
 /*   260 */    50,   23,   24,   19,   19,   62,   23,   24,    1,    2,
 /*   270 */     3,    4,   51,   19,   19,   63,   19,   51,   66,   59,
 /*   280 */    60,   61,   51,   40,   41,   19,   51,   19,   51,   69,
 /*   290 */    23,   24,   72,   50,   21,   52,   76,   20,   78,   59,
 /*   300 */    60,   61,   50,    1,    1,   19,   19,   40,   41,   69,
 /*   310 */    19,   19,   72,   19,   19,   19,   76,   50,   78,   52,
 /*   320 */    59,   60,   61,   19,   19,   19,   19,   79,   79,   79,
 /*   330 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   340 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   350 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   360 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   370 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   380 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   390 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   400 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   410 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   420 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   430 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   440 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   450 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   460 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   470 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   480 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   490 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   500 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   510 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   520 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   530 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   540 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   550 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   560 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   570 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   580 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   590 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   600 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   610 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   620 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   630 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   640 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   650 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   660 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   670 */    69,   79,   79,   72,   79,   79,   79,   76,   79,   78,
 /*   680 */    59,   60,   61,   79,   79,   79,   79,   79,   79,   79,
 /*   690 */    69,   79,   79,   72,   60,   79,   79,   76,   64,   78,
 /*   700 */    79,   79,   68,   69,   70,   71,   72,   79,   79,   79,
 /*   710 */    79,   60,   79,   79,   79,   64,   79,   79,   79,   68,
 /*   720 */    69,   70,   71,   72,   79,   79,   79,   79,   37,   79,
 /*   730 */    79,   40,   41,   42,   43,   44,   79,   79,   79,   79,
 /*   740 */    79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
 /*   750 */    79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
 /*   760 */    79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
 /*   770 */    79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
 /*   780 */    79,   79,   79,   79,   79,   56,   56,   56,   56,   56,
 /*   790 */    56,   56,
};
#define YY_SHIFT_COUNT    (102)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (691)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */    15,  159,  141,  192,  192,  192,  192,  192,  192,  192,
 /*    10 */   192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
 /*    20 */   192,  192,  210,  192,  243,  267,  175,   10,   68,   68,
 /*    30 */    68,   68,   11,   37,   44,   48,   48,   53,   77,   77,
 /*    40 */   200,  205,  238,    3,  130,   38,  169,  201,  207,  179,
 /*    50 */   202,    0,   25,   52,   79,   79,   79,   79,   97,  115,
 /*    60 */   131,  131,  691,  691,  691,  691,   57,    4,    4,   51,
 /*    70 */   170,  221,  226,  231,  244,  245,  254,  255,  257,  266,
 /*    80 */   268,  235,  237,  273,  273,  277,  252,  302,  303,  277,
 /*    90 */   286,  287,  291,  292,  294,  295,  296,  304,  305,  306,
 /*   100 */   245,  307,  244,
};
#define YY_REDUCE_COUNT (50)
#define YY_REDUCE_MIN   (-60)
#define YY_REDUCE_MAX   (651)
static const short yy_reduce_ofst[] = {
 /*     0 */   -53,  -59,  158,  220,  240,  261,  281,  301,  321,  341,
 /*    10 */   361,  381,  401,  421,  441,  461,  481,  501,  521,  541,
 /*    20 */   561,  581,  601,  621,  634,  651,  -51,  -37,  111,  129,
 /*    30 */   153,  180,  -60,  212,    1,  -56,   49,   62,   35,   54,
 /*    40 */     7,    7,    7,  122,    7,  119,  139,  143,  136,  177,
 /*    50 */   203,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
 /*    10 */   230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
 /*    20 */   230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
 /*    30 */   230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
 /*    40 */   230,  230,  307,  270,  230,  230,  230,  304,  230,  307,
 /*    50 */   230,  230,  230,  230,  278,  302,  303,  301,  300,  299,
 /*    60 */   294,  293,  298,  297,  296,  295,  292,  287,  288,  230,
 /*    70 */   230,  230,  230,  230,  234,  244,  230,  230,  230,  262,
 /*    80 */   230,  230,  230,  307,  230,  305,  230,  230,  230,  270,
 /*    90 */   230,  230,  261,  230,  260,  230,  259,  230,  258,  257,
 /*   100 */   245,  230,  235,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  flow_parserARG_SDECL                /* A place to hold %extra_argument */
  flow_parserCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#ifndef NDEBUG
#include <stdio.h>
#include <assert.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void flow_parserTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "ID",
  /*    2 */ "STRING",
  /*    3 */ "INTEGER",
  /*    4 */ "FLOAT",
  /*    5 */ "SYMBOL",
  /*    6 */ "NODE",
  /*    7 */ "CONTAINER",
  /*    8 */ "ENTRY",
  /*    9 */ "IMPORT",
  /*   10 */ "DEFINE",
  /*   11 */ "OUTPUT",
  /*   12 */ "RETURN",
  /*   13 */ "ERROR",
  /*   14 */ "ENDPOINT",
  /*   15 */ "IMAGE",
  /*   16 */ "MOUNT",
  /*   17 */ "ENVIRONMENT",
  /*   18 */ "INPUT",
  /*   19 */ "SEMICOLON",
  /*   20 */ "DOT",
  /*   21 */ "AT",
  /*   22 */ "COMMA",
  /*   23 */ "EQUALS",
  /*   24 */ "COLON",
  /*   25 */ "QUESTION",
  /*   26 */ "OR",
  /*   27 */ "AND",
  /*   28 */ "BAR",
  /*   29 */ "CARET",
  /*   30 */ "AMP",
  /*   31 */ "NE",
  /*   32 */ "EQ",
  /*   33 */ "GT",
  /*   34 */ "LT",
  /*   35 */ "GE",
  /*   36 */ "LE",
  /*   37 */ "COMP",
  /*   38 */ "SHR",
  /*   39 */ "SHL",
  /*   40 */ "PLUS",
  /*   41 */ "MINUS",
  /*   42 */ "STAR",
  /*   43 */ "SLASH",
  /*   44 */ "PERCENT",
  /*   45 */ "BANG",
  /*   46 */ "TILDA",
  /*   47 */ "DOLLAR",
  /*   48 */ "HASH",
  /*   49 */ "UMINUS",
  /*   50 */ "OPENPAR",
  /*   51 */ "CLOSEPAR",
  /*   52 */ "OPENBRA",
  /*   53 */ "CLOSEBRA",
  /*   54 */ "OPENSQB",
  /*   55 */ "CLOSESQB",
  /*   56 */ "main",
  /*   57 */ "flow",
  /*   58 */ "stmt",
  /*   59 */ "vall",
  /*   60 */ "dtid",
  /*   61 */ "fldr",
  /*   62 */ "blck",
  /*   63 */ "list",
  /*   64 */ "blck2",
  /*   65 */ "list2",
  /*   66 */ "elem",
  /*   67 */ "elem2",
  /*   68 */ "lblk",
  /*   69 */ "valx",
  /*   70 */ "oexp",
  /*   71 */ "rexp",
  /*   72 */ "valn",
  /*   73 */ "fldm",
  /*   74 */ "fldd",
  /*   75 */ "eqsc",
  /*   76 */ "fldx",
  /*   77 */ "fldra",
  /*   78 */ "fldn",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "main ::= flow",
 /*   1 */ "flow ::= stmt",
 /*   2 */ "flow ::= flow stmt",
 /*   3 */ "stmt ::= ID vall SEMICOLON",
 /*   4 */ "stmt ::= ID dtid OPENPAR fldr CLOSEPAR blck",
 /*   5 */ "stmt ::= ID dtid blck",
 /*   6 */ "stmt ::= stmt SEMICOLON",
 /*   7 */ "blck ::= OPENBRA list CLOSEBRA",
 /*   8 */ "blck ::= OPENBRA CLOSEBRA",
 /*   9 */ "blck2 ::= OPENBRA list2 CLOSEBRA",
 /*  10 */ "blck2 ::= OPENBRA CLOSEBRA",
 /*  11 */ "list ::= elem",
 /*  12 */ "list ::= list elem",
 /*  13 */ "list2 ::= elem2",
 /*  14 */ "list2 ::= list2 elem2",
 /*  15 */ "elem ::= ID blck2",
 /*  16 */ "elem ::= ID lblk",
 /*  17 */ "elem ::= ID valx SEMICOLON",
 /*  18 */ "elem ::= ID EQUALS valx SEMICOLON",
 /*  19 */ "elem ::= ID COLON valx SEMICOLON",
 /*  20 */ "elem ::= ID oexp SEMICOLON",
 /*  21 */ "elem ::= ID rexp SEMICOLON",
 /*  22 */ "elem ::= elem SEMICOLON",
 /*  23 */ "lblk ::= ID blck2",
 /*  24 */ "elem2 ::= ID blck2",
 /*  25 */ "elem2 ::= ID lblk",
 /*  26 */ "elem2 ::= ID valx SEMICOLON",
 /*  27 */ "elem2 ::= ID EQUALS valx SEMICOLON",
 /*  28 */ "elem2 ::= ID COLON valx SEMICOLON",
 /*  29 */ "elem2 ::= elem SEMICOLON",
 /*  30 */ "valn ::= INTEGER",
 /*  31 */ "valn ::= FLOAT",
 /*  32 */ "valn ::= PLUS valn",
 /*  33 */ "valn ::= MINUS valn",
 /*  34 */ "valx ::= STRING",
 /*  35 */ "valx ::= valn",
 /*  36 */ "vall ::= valx",
 /*  37 */ "vall ::= dtid",
 /*  38 */ "rexp ::= OPENPAR fldm CLOSEPAR",
 /*  39 */ "rexp ::= OPENPAR ID AT CLOSEPAR",
 /*  40 */ "oexp ::= dtid OPENPAR ID AT CLOSEPAR",
 /*  41 */ "oexp ::= dtid OPENPAR fldm CLOSEPAR",
 /*  42 */ "fldm ::= fldd",
 /*  43 */ "fldm ::= fldm COMMA fldd",
 /*  44 */ "fldd ::= ID eqsc OPENPAR fldm CLOSEPAR",
 /*  45 */ "fldd ::= ID eqsc fldr",
 /*  46 */ "fldr ::= vall",
 /*  47 */ "fldr ::= fldx",
 /*  48 */ "fldr ::= OPENPAR fldr CLOSEPAR",
 /*  49 */ "fldr ::= TILDA ID OPENPAR CLOSEPAR",
 /*  50 */ "fldr ::= TILDA ID OPENPAR fldra CLOSEPAR",
 /*  51 */ "fldr ::= HASH fldx",
 /*  52 */ "fldr ::= DOLLAR fldx",
 /*  53 */ "fldr ::= BANG fldr",
 /*  54 */ "fldr ::= fldr PLUS fldr",
 /*  55 */ "fldr ::= fldr MINUS fldr",
 /*  56 */ "fldr ::= fldr SLASH fldr",
 /*  57 */ "fldr ::= fldr STAR fldr",
 /*  58 */ "fldr ::= fldr PERCENT fldr",
 /*  59 */ "fldr ::= fldr COMP fldr",
 /*  60 */ "fldr ::= fldr EQ fldr",
 /*  61 */ "fldr ::= fldr NE fldr",
 /*  62 */ "fldr ::= fldr LT fldr",
 /*  63 */ "fldr ::= fldr GT fldr",
 /*  64 */ "fldr ::= fldr LE fldr",
 /*  65 */ "fldr ::= fldr GE fldr",
 /*  66 */ "fldr ::= fldr AND fldr",
 /*  67 */ "fldr ::= fldr OR fldr",
 /*  68 */ "fldr ::= fldr QUESTION fldr COLON fldr",
 /*  69 */ "fldra ::= fldr",
 /*  70 */ "fldra ::= fldra COMMA fldr",
 /*  71 */ "fldx ::= fldn",
 /*  72 */ "fldx ::= fldn dtid",
 /*  73 */ "fldn ::= ID AT",
 /*  74 */ "dtid ::= ID",
 /*  75 */ "dtid ::= dtid DOT ID",
 /*  76 */ "eqsc ::= EQUALS",
 /*  77 */ "eqsc ::= COLON",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to flow_parserAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void flow_parserInit(void *yypRawParser flow_parserCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  flow_parserCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef flow_parser_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to flow_parser and flow_parserFree.
*/
void *flow_parserAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) flow_parserCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    flow_parserCTX_STORE
    flow_parserInit(yypParser flow_parserCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* flow_parser_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  flow_parserARG_FETCH
  flow_parserCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void flow_parserFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef flow_parser_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void flow_parserFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  flow_parserFinalize(p);
  (*freeProc)(p);
}
#endif /* flow_parser_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int flow_parserStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int flow_parserCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   flow_parserARG_FETCH
   flow_parserCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   flow_parserARG_STORE /* Suppress warning about unused %extra_argument var */
   flow_parserCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  flow_parserTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    56,  /* (0) main ::= flow */
    57,  /* (1) flow ::= stmt */
    57,  /* (2) flow ::= flow stmt */
    58,  /* (3) stmt ::= ID vall SEMICOLON */
    58,  /* (4) stmt ::= ID dtid OPENPAR fldr CLOSEPAR blck */
    58,  /* (5) stmt ::= ID dtid blck */
    58,  /* (6) stmt ::= stmt SEMICOLON */
    62,  /* (7) blck ::= OPENBRA list CLOSEBRA */
    62,  /* (8) blck ::= OPENBRA CLOSEBRA */
    64,  /* (9) blck2 ::= OPENBRA list2 CLOSEBRA */
    64,  /* (10) blck2 ::= OPENBRA CLOSEBRA */
    63,  /* (11) list ::= elem */
    63,  /* (12) list ::= list elem */
    65,  /* (13) list2 ::= elem2 */
    65,  /* (14) list2 ::= list2 elem2 */
    66,  /* (15) elem ::= ID blck2 */
    66,  /* (16) elem ::= ID lblk */
    66,  /* (17) elem ::= ID valx SEMICOLON */
    66,  /* (18) elem ::= ID EQUALS valx SEMICOLON */
    66,  /* (19) elem ::= ID COLON valx SEMICOLON */
    66,  /* (20) elem ::= ID oexp SEMICOLON */
    66,  /* (21) elem ::= ID rexp SEMICOLON */
    66,  /* (22) elem ::= elem SEMICOLON */
    68,  /* (23) lblk ::= ID blck2 */
    67,  /* (24) elem2 ::= ID blck2 */
    67,  /* (25) elem2 ::= ID lblk */
    67,  /* (26) elem2 ::= ID valx SEMICOLON */
    67,  /* (27) elem2 ::= ID EQUALS valx SEMICOLON */
    67,  /* (28) elem2 ::= ID COLON valx SEMICOLON */
    67,  /* (29) elem2 ::= elem SEMICOLON */
    72,  /* (30) valn ::= INTEGER */
    72,  /* (31) valn ::= FLOAT */
    72,  /* (32) valn ::= PLUS valn */
    72,  /* (33) valn ::= MINUS valn */
    69,  /* (34) valx ::= STRING */
    69,  /* (35) valx ::= valn */
    59,  /* (36) vall ::= valx */
    59,  /* (37) vall ::= dtid */
    71,  /* (38) rexp ::= OPENPAR fldm CLOSEPAR */
    71,  /* (39) rexp ::= OPENPAR ID AT CLOSEPAR */
    70,  /* (40) oexp ::= dtid OPENPAR ID AT CLOSEPAR */
    70,  /* (41) oexp ::= dtid OPENPAR fldm CLOSEPAR */
    73,  /* (42) fldm ::= fldd */
    73,  /* (43) fldm ::= fldm COMMA fldd */
    74,  /* (44) fldd ::= ID eqsc OPENPAR fldm CLOSEPAR */
    74,  /* (45) fldd ::= ID eqsc fldr */
    61,  /* (46) fldr ::= vall */
    61,  /* (47) fldr ::= fldx */
    61,  /* (48) fldr ::= OPENPAR fldr CLOSEPAR */
    61,  /* (49) fldr ::= TILDA ID OPENPAR CLOSEPAR */
    61,  /* (50) fldr ::= TILDA ID OPENPAR fldra CLOSEPAR */
    61,  /* (51) fldr ::= HASH fldx */
    61,  /* (52) fldr ::= DOLLAR fldx */
    61,  /* (53) fldr ::= BANG fldr */
    61,  /* (54) fldr ::= fldr PLUS fldr */
    61,  /* (55) fldr ::= fldr MINUS fldr */
    61,  /* (56) fldr ::= fldr SLASH fldr */
    61,  /* (57) fldr ::= fldr STAR fldr */
    61,  /* (58) fldr ::= fldr PERCENT fldr */
    61,  /* (59) fldr ::= fldr COMP fldr */
    61,  /* (60) fldr ::= fldr EQ fldr */
    61,  /* (61) fldr ::= fldr NE fldr */
    61,  /* (62) fldr ::= fldr LT fldr */
    61,  /* (63) fldr ::= fldr GT fldr */
    61,  /* (64) fldr ::= fldr LE fldr */
    61,  /* (65) fldr ::= fldr GE fldr */
    61,  /* (66) fldr ::= fldr AND fldr */
    61,  /* (67) fldr ::= fldr OR fldr */
    61,  /* (68) fldr ::= fldr QUESTION fldr COLON fldr */
    77,  /* (69) fldra ::= fldr */
    77,  /* (70) fldra ::= fldra COMMA fldr */
    76,  /* (71) fldx ::= fldn */
    76,  /* (72) fldx ::= fldn dtid */
    78,  /* (73) fldn ::= ID AT */
    60,  /* (74) dtid ::= ID */
    60,  /* (75) dtid ::= dtid DOT ID */
    75,  /* (76) eqsc ::= EQUALS */
    75,  /* (77) eqsc ::= COLON */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) main ::= flow */
   -1,  /* (1) flow ::= stmt */
   -2,  /* (2) flow ::= flow stmt */
   -3,  /* (3) stmt ::= ID vall SEMICOLON */
   -6,  /* (4) stmt ::= ID dtid OPENPAR fldr CLOSEPAR blck */
   -3,  /* (5) stmt ::= ID dtid blck */
   -2,  /* (6) stmt ::= stmt SEMICOLON */
   -3,  /* (7) blck ::= OPENBRA list CLOSEBRA */
   -2,  /* (8) blck ::= OPENBRA CLOSEBRA */
   -3,  /* (9) blck2 ::= OPENBRA list2 CLOSEBRA */
   -2,  /* (10) blck2 ::= OPENBRA CLOSEBRA */
   -1,  /* (11) list ::= elem */
   -2,  /* (12) list ::= list elem */
   -1,  /* (13) list2 ::= elem2 */
   -2,  /* (14) list2 ::= list2 elem2 */
   -2,  /* (15) elem ::= ID blck2 */
   -2,  /* (16) elem ::= ID lblk */
   -3,  /* (17) elem ::= ID valx SEMICOLON */
   -4,  /* (18) elem ::= ID EQUALS valx SEMICOLON */
   -4,  /* (19) elem ::= ID COLON valx SEMICOLON */
   -3,  /* (20) elem ::= ID oexp SEMICOLON */
   -3,  /* (21) elem ::= ID rexp SEMICOLON */
   -2,  /* (22) elem ::= elem SEMICOLON */
   -2,  /* (23) lblk ::= ID blck2 */
   -2,  /* (24) elem2 ::= ID blck2 */
   -2,  /* (25) elem2 ::= ID lblk */
   -3,  /* (26) elem2 ::= ID valx SEMICOLON */
   -4,  /* (27) elem2 ::= ID EQUALS valx SEMICOLON */
   -4,  /* (28) elem2 ::= ID COLON valx SEMICOLON */
   -2,  /* (29) elem2 ::= elem SEMICOLON */
   -1,  /* (30) valn ::= INTEGER */
   -1,  /* (31) valn ::= FLOAT */
   -2,  /* (32) valn ::= PLUS valn */
   -2,  /* (33) valn ::= MINUS valn */
   -1,  /* (34) valx ::= STRING */
   -1,  /* (35) valx ::= valn */
   -1,  /* (36) vall ::= valx */
   -1,  /* (37) vall ::= dtid */
   -3,  /* (38) rexp ::= OPENPAR fldm CLOSEPAR */
   -4,  /* (39) rexp ::= OPENPAR ID AT CLOSEPAR */
   -5,  /* (40) oexp ::= dtid OPENPAR ID AT CLOSEPAR */
   -4,  /* (41) oexp ::= dtid OPENPAR fldm CLOSEPAR */
   -1,  /* (42) fldm ::= fldd */
   -3,  /* (43) fldm ::= fldm COMMA fldd */
   -5,  /* (44) fldd ::= ID eqsc OPENPAR fldm CLOSEPAR */
   -3,  /* (45) fldd ::= ID eqsc fldr */
   -1,  /* (46) fldr ::= vall */
   -1,  /* (47) fldr ::= fldx */
   -3,  /* (48) fldr ::= OPENPAR fldr CLOSEPAR */
   -4,  /* (49) fldr ::= TILDA ID OPENPAR CLOSEPAR */
   -5,  /* (50) fldr ::= TILDA ID OPENPAR fldra CLOSEPAR */
   -2,  /* (51) fldr ::= HASH fldx */
   -2,  /* (52) fldr ::= DOLLAR fldx */
   -2,  /* (53) fldr ::= BANG fldr */
   -3,  /* (54) fldr ::= fldr PLUS fldr */
   -3,  /* (55) fldr ::= fldr MINUS fldr */
   -3,  /* (56) fldr ::= fldr SLASH fldr */
   -3,  /* (57) fldr ::= fldr STAR fldr */
   -3,  /* (58) fldr ::= fldr PERCENT fldr */
   -3,  /* (59) fldr ::= fldr COMP fldr */
   -3,  /* (60) fldr ::= fldr EQ fldr */
   -3,  /* (61) fldr ::= fldr NE fldr */
   -3,  /* (62) fldr ::= fldr LT fldr */
   -3,  /* (63) fldr ::= fldr GT fldr */
   -3,  /* (64) fldr ::= fldr LE fldr */
   -3,  /* (65) fldr ::= fldr GE fldr */
   -3,  /* (66) fldr ::= fldr AND fldr */
   -3,  /* (67) fldr ::= fldr OR fldr */
   -5,  /* (68) fldr ::= fldr QUESTION fldr COLON fldr */
   -1,  /* (69) fldra ::= fldr */
   -3,  /* (70) fldra ::= fldra COMMA fldr */
   -1,  /* (71) fldx ::= fldn */
   -2,  /* (72) fldx ::= fldn dtid */
   -2,  /* (73) fldn ::= ID AT */
   -1,  /* (74) dtid ::= ID */
   -3,  /* (75) dtid ::= dtid DOT ID */
   -1,  /* (76) eqsc ::= EQUALS */
   -1,  /* (77) eqsc ::= COLON */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  flow_parserTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  flow_parserCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  flow_parserARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;
  assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
#ifndef NDEBUG
  if( yyTraceFILE ){
    yysize = yyRuleInfoNRhs[yyruleno];
    if( yysize ){
      fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
        yyTracePrompt,
        yyruleno, yyRuleName[yyruleno],
        yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
        yymsp[yysize].stateno);
    }else{
      fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
        yyTracePrompt, yyruleno, yyRuleName[yyruleno],
        yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
    }
  }
#endif /* NDEBUG */

  /* Check that the stack is large enough to grow by a single entry
  ** if the RHS of the rule is empty.  This ensures that there is room
  ** enough on the stack to push the LHS value */
  if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
    if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
      yypParser->yyhwm++;
      assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack));
    }
#endif
#if YYSTACKDEPTH>0 
    if( yypParser->yytos>=yypParser->yystackEnd ){
      yyStackOverflow(yypParser);
      /* The call to yyStackOverflow() above pops the stack until it is
      ** empty, causing the main parser loop to exit.  So the return value
      ** is never used and does not matter. */
      return 0;
    }
#else
    if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
      if( yyGrowStack(yypParser) ){
        yyStackOverflow(yypParser);
        /* The call to yyStackOverflow() above pops the stack until it is
        ** empty, causing the main parser loop to exit.  So the return value
        ** is never used and does not matter. */
        return 0;
      }
      yymsp = yypParser->yytos;
    }
#endif
  }

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* main ::= flow */
#line 46 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_ACCEPT, yymsp[0].minor.yy0); }
#line 1384 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 1: /* flow ::= stmt */
#line 48 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_flow, yymsp[0].minor.yy0); }
#line 1390 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 2: /* flow ::= flow stmt */
      case 12: /* list ::= list elem */ yytestcase(yyruleno==12);
      case 14: /* list2 ::= list2 elem2 */ yytestcase(yyruleno==14);
#line 49 "flow-parser.y"
{ yylhsminor.yy0 = ast->nappend(yymsp[-1].minor.yy0, yymsp[0].minor.yy0); }
#line 1398 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 3: /* stmt ::= ID vall SEMICOLON */
#line 51 "flow-parser.y"
{ yylhsminor.yy0 = ast->stmt_keyw(yymsp[-2].minor.yy0) == FTK_IMPORT? ast->node(FTK_IMPORT, yymsp[-1].minor.yy0): ast->node(ast->stmt_keyw(yymsp[-2].minor.yy0), yymsp[-2].minor.yy0, yymsp[-1].minor.yy0); 
                                                                 ast->expect(yylhsminor.yy0, {FTK_DEFINE, FTK_IMPORT}, "import directive or variable definition expected"); }
#line 1405 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 4: /* stmt ::= ID dtid OPENPAR fldr CLOSEPAR blck */
#line 53 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(ast->stmt_keyw(yymsp[-5].minor.yy0), yymsp[-5].minor.yy0, yymsp[-4].minor.yy0, yymsp[0].minor.yy0, yymsp[-2].minor.yy0); ast->expect(yylhsminor.yy0, FTK_NODE, "expected \"node\" keyword"); }
#line 1411 "flow-parser.c"
  yymsp[-5].minor.yy0 = yylhsminor.yy0;
        break;
      case 5: /* stmt ::= ID dtid blck */
#line 54 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(ast->stmt_keyw(yymsp[-2].minor.yy0), yymsp[-2].minor.yy0, yymsp[-1].minor.yy0, yymsp[0].minor.yy0); 
                                                                 ast->expect(yylhsminor.yy0, {FTK_CONTAINER, FTK_NODE, FTK_ENTRY}, "expected \"node\", \"entry\" or \"container\" here"); }
#line 1418 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 6: /* stmt ::= stmt SEMICOLON */
      case 22: /* elem ::= elem SEMICOLON */ yytestcase(yyruleno==22);
      case 29: /* elem2 ::= elem SEMICOLON */ yytestcase(yyruleno==29);
      case 73: /* fldn ::= ID AT */ yytestcase(yyruleno==73);
#line 56 "flow-parser.y"
{ yylhsminor.yy0 = yymsp[-1].minor.yy0; }
#line 1427 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 7: /* blck ::= OPENBRA list CLOSEBRA */
      case 9: /* blck2 ::= OPENBRA list2 CLOSEBRA */ yytestcase(yyruleno==9);
      case 48: /* fldr ::= OPENPAR fldr CLOSEPAR */ yytestcase(yyruleno==48);
#line 58 "flow-parser.y"
{ yymsp[-2].minor.yy0 = yymsp[-1].minor.yy0; }
#line 1435 "flow-parser.c"
        break;
      case 8: /* blck ::= OPENBRA CLOSEBRA */
      case 10: /* blck2 ::= OPENBRA CLOSEBRA */ yytestcase(yyruleno==10);
#line 59 "flow-parser.y"
{ yylhsminor.yy0 = ast->chtype(yymsp[-1].minor.yy0, FTK_blck); }
#line 1441 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 11: /* list ::= elem */
      case 13: /* list2 ::= elem2 */ yytestcase(yyruleno==13);
#line 66 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_blck, yymsp[0].minor.yy0); }
#line 1448 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 15: /* elem ::= ID blck2 */
      case 16: /* elem ::= ID lblk */ yytestcase(yyruleno==16);
      case 24: /* elem2 ::= ID blck2 */ yytestcase(yyruleno==24);
      case 25: /* elem2 ::= ID lblk */ yytestcase(yyruleno==25);
#line 74 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-1].minor.yy0, yymsp[0].minor.yy0); }
#line 1457 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 17: /* elem ::= ID valx SEMICOLON */
      case 20: /* elem ::= ID oexp SEMICOLON */ yytestcase(yyruleno==20);
      case 21: /* elem ::= ID rexp SEMICOLON */ yytestcase(yyruleno==21);
      case 26: /* elem2 ::= ID valx SEMICOLON */ yytestcase(yyruleno==26);
#line 76 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-2].minor.yy0, yymsp[-1].minor.yy0); }
#line 1466 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 18: /* elem ::= ID EQUALS valx SEMICOLON */
      case 19: /* elem ::= ID COLON valx SEMICOLON */ yytestcase(yyruleno==19);
      case 27: /* elem2 ::= ID EQUALS valx SEMICOLON */ yytestcase(yyruleno==27);
      case 28: /* elem2 ::= ID COLON valx SEMICOLON */ yytestcase(yyruleno==28);
#line 77 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-3].minor.yy0, yymsp[-1].minor.yy0); }
#line 1475 "flow-parser.c"
  yymsp[-3].minor.yy0 = yylhsminor.yy0;
        break;
      case 23: /* lblk ::= ID blck2 */
#line 83 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_lblk, yymsp[-1].minor.yy0, yymsp[0].minor.yy0); }
#line 1481 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 30: /* valn ::= INTEGER */
      case 31: /* valn ::= FLOAT */ yytestcase(yyruleno==31);
      case 34: /* valx ::= STRING */ yytestcase(yyruleno==34);
      case 35: /* valx ::= valn */ yytestcase(yyruleno==35);
      case 36: /* vall ::= valx */ yytestcase(yyruleno==36);
      case 37: /* vall ::= dtid */ yytestcase(yyruleno==37);
      case 46: /* fldr ::= vall */ yytestcase(yyruleno==46);
      case 47: /* fldr ::= fldx */ yytestcase(yyruleno==47);
      case 71: /* fldx ::= fldn */ yytestcase(yyruleno==71);
#line 96 "flow-parser.y"
{ yylhsminor.yy0 = yymsp[0].minor.yy0; }
#line 1495 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 32: /* valn ::= PLUS valn */
#line 98 "flow-parser.y"
{ yymsp[-1].minor.yy0 = yymsp[0].minor.yy0; }
#line 1501 "flow-parser.c"
        break;
      case 33: /* valn ::= MINUS valn */
#line 99 "flow-parser.y"
{ yymsp[-1].minor.yy0 = ast->negate(yymsp[0].minor.yy0); }
#line 1506 "flow-parser.c"
        break;
      case 38: /* rexp ::= OPENPAR fldm CLOSEPAR */
#line 113 "flow-parser.y"
{ yymsp[-2].minor.yy0 = ast->node(FTK_RETURN, yymsp[-1].minor.yy0); }
#line 1511 "flow-parser.c"
        break;
      case 39: /* rexp ::= OPENPAR ID AT CLOSEPAR */
#line 114 "flow-parser.y"
{ yymsp[-3].minor.yy0 = ast->node(FTK_RETURN, yymsp[-2].minor.yy0); }
#line 1516 "flow-parser.c"
        break;
      case 40: /* oexp ::= dtid OPENPAR ID AT CLOSEPAR */
#line 118 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_OUTPUT, yymsp[-4].minor.yy0, yymsp[-2].minor.yy0); }
#line 1521 "flow-parser.c"
  yymsp[-4].minor.yy0 = yylhsminor.yy0;
        break;
      case 41: /* oexp ::= dtid OPENPAR fldm CLOSEPAR */
#line 119 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_OUTPUT, yymsp[-3].minor.yy0, yymsp[-1].minor.yy0); }
#line 1527 "flow-parser.c"
  yymsp[-3].minor.yy0 = yylhsminor.yy0;
        break;
      case 42: /* fldm ::= fldd */
#line 121 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldm, yymsp[0].minor.yy0); }
#line 1533 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 43: /* fldm ::= fldm COMMA fldd */
      case 70: /* fldra ::= fldra COMMA fldr */ yytestcase(yyruleno==70);
      case 75: /* dtid ::= dtid DOT ID */ yytestcase(yyruleno==75);
#line 122 "flow-parser.y"
{ yylhsminor.yy0 = ast->nappend(yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1541 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 44: /* fldd ::= ID eqsc OPENPAR fldm CLOSEPAR */
#line 126 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldd, yymsp[-4].minor.yy0, yymsp[-1].minor.yy0); ast->chinteger(yylhsminor.yy0, ast->at(yymsp[-3].minor.yy0).token.integer_value); }
#line 1547 "flow-parser.c"
  yymsp[-4].minor.yy0 = yylhsminor.yy0;
        break;
      case 45: /* fldd ::= ID eqsc fldr */
#line 127 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldd, yymsp[-2].minor.yy0, yymsp[0].minor.yy0); ast->chinteger(yylhsminor.yy0, ast->at(yymsp[-1].minor.yy0).token.integer_value); }
#line 1553 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 49: /* fldr ::= TILDA ID OPENPAR CLOSEPAR */
#line 134 "flow-parser.y"
{ yymsp[-3].minor.yy0 = ast->node(FTK_fldr, yymsp[-2].minor.yy0); }
#line 1559 "flow-parser.c"
        break;
      case 50: /* fldr ::= TILDA ID OPENPAR fldra CLOSEPAR */
#line 135 "flow-parser.y"
{ yymsp[-4].minor.yy0 = ast->nprepend(yymsp[-1].minor.yy0, yymsp[-3].minor.yy0); }
#line 1564 "flow-parser.c"
        break;
      case 51: /* fldr ::= HASH fldx */
      case 52: /* fldr ::= DOLLAR fldx */ yytestcase(yyruleno==52);
      case 53: /* fldr ::= BANG fldr */ yytestcase(yyruleno==53);
#line 136 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldr, yymsp[-1].minor.yy0, yymsp[0].minor.yy0); }
#line 1571 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 54: /* fldr ::= fldr PLUS fldr */
      case 55: /* fldr ::= fldr MINUS fldr */ yytestcase(yyruleno==55);
      case 56: /* fldr ::= fldr SLASH fldr */ yytestcase(yyruleno==56);
      case 57: /* fldr ::= fldr STAR fldr */ yytestcase(yyruleno==57);
      case 58: /* fldr ::= fldr PERCENT fldr */ yytestcase(yyruleno==58);
      case 59: /* fldr ::= fldr COMP fldr */ yytestcase(yyruleno==59);
      case 60: /* fldr ::= fldr EQ fldr */ yytestcase(yyruleno==60);
      case 61: /* fldr ::= fldr NE fldr */ yytestcase(yyruleno==61);
      case 62: /* fldr ::= fldr LT fldr */ yytestcase(yyruleno==62);
      case 63: /* fldr ::= fldr GT fldr */ yytestcase(yyruleno==63);
      case 64: /* fldr ::= fldr LE fldr */ yytestcase(yyruleno==64);
      case 65: /* fldr ::= fldr GE fldr */ yytestcase(yyruleno==65);
      case 66: /* fldr ::= fldr AND fldr */ yytestcase(yyruleno==66);
      case 67: /* fldr ::= fldr OR fldr */ yytestcase(yyruleno==67);
#line 139 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldr, yymsp[-1].minor.yy0, yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1590 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 68: /* fldr ::= fldr QUESTION fldr COLON fldr */
#line 153 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldr, yymsp[-3].minor.yy0, yymsp[-4].minor.yy0, yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1596 "flow-parser.c"
  yymsp[-4].minor.yy0 = yylhsminor.yy0;
        break;
      case 69: /* fldra ::= fldr */
#line 155 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldr, yymsp[0].minor.yy0); }
#line 1602 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 72: /* fldx ::= fldn dtid */
#line 161 "flow-parser.y"
{ yylhsminor.yy0 = ast->chtype(ast->nprepend(yymsp[0].minor.yy0, yymsp[-1].minor.yy0), FTK_fldx); }
#line 1608 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 74: /* dtid ::= ID */
#line 169 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_dtid, yymsp[0].minor.yy0); }
#line 1614 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 76: /* eqsc ::= EQUALS */
      case 77: /* eqsc ::= COLON */ yytestcase(yyruleno==77);
#line 174 "flow-parser.y"
{ ast->chinteger(yymsp[0].minor.yy0, 0); }
#line 1621 "flow-parser.c"
        break;
      default:
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  flow_parserARG_FETCH
  flow_parserCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 42 "flow-parser.y"

    ast->node(FTK_SYNTAX_ERROR, (int) ast->store.size());
#line 1668 "flow-parser.c"
/************ End %parse_failure code *****************************************/
  flow_parserARG_STORE /* Suppress warning about unused %extra_argument variable */
  flow_parserCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  flow_parserTOKENTYPE yyminor         /* The minor type of the error token */
){
  flow_parserARG_FETCH
  flow_parserCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 36 "flow-parser.y"

    ast->node(FTK_SYNTAX_ERROR, (int) ast->store.size());
#line 1690 "flow-parser.c"
/************ End %syntax_error code ******************************************/
  flow_parserARG_STORE /* Suppress warning about unused %extra_argument variable */
  flow_parserCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  flow_parserARG_FETCH
  flow_parserCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
#line 39 "flow-parser.y"

    //std::cerr << "parsed just fine, ast size: " << ast->store.size() << " root: " << ast->store.back().children[0] << "\n";
#line 1719 "flow-parser.c"
/*********** End %parse_accept code *******************************************/
  flow_parserARG_STORE /* Suppress warning about unused %extra_argument variable */
  flow_parserCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "flow_parserAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void flow_parser(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  flow_parserTOKENTYPE yyminor       /* The value for the token */
  flow_parserARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  flow_parserCTX_FETCH
  flow_parserARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  do{
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      yyact = yy_reduce(yypParser,yyact-YY_MIN_REDUCE,yymajor,
                        yyminor flow_parserCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos >= yypParser->yystack
            && (yyact = yy_find_reduce_action(
                        yypParser->yytos->stateno,
                        YYERRORSYMBOL)) > YY_MAX_SHIFTREDUCE
        ){
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos < yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }while( yypParser->yytos>yypParser->yystack );
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int flow_parserFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
