/* This file is automatically generated by Lemon from input grammar
** source file "flow-parser.y". */
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 28 "flow-parser.y"

#include <iostream>
#include "flow-ast.H"
#define YYNOERRORRECOVERY
#line 34 "flow-parser.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef FTK_ID
#define FTK_ID                              1
#define FTK_STRING                          2
#define FTK_INTEGER                         3
#define FTK_FLOAT                           4
#define FTK_SYMBOL                          5
#define FTK_NODE                            6
#define FTK_CONTAINER                       7
#define FTK_ENTRY                           8
#define FTK_IMPORT                          9
#define FTK_DEFINE                         10
#define FTK_OUTPUT                         11
#define FTK_RETURN                         12
#define FTK_ERROR                          13
#define FTK_MOUNT                          14
#define FTK_ENVIRONMENT                    15
#define FTK_INPUT                          16
#define FTK_HEADERS                        17
#define FTK_SEMICOLON                      18
#define FTK_DOT                            19
#define FTK_AT                             20
#define FTK_COMMA                          21
#define FTK_EQUALS                         22
#define FTK_COLON                          23
#define FTK_QUESTION                       24
#define FTK_OR                             25
#define FTK_AND                            26
#define FTK_BAR                            27
#define FTK_CARET                          28
#define FTK_AMP                            29
#define FTK_NE                             30
#define FTK_EQ                             31
#define FTK_GT                             32
#define FTK_LT                             33
#define FTK_GE                             34
#define FTK_LE                             35
#define FTK_COMP                           36
#define FTK_SHR                            37
#define FTK_SHL                            38
#define FTK_PLUS                           39
#define FTK_MINUS                          40
#define FTK_STAR                           41
#define FTK_SLASH                          42
#define FTK_PERCENT                        43
#define FTK_BANG                           44
#define FTK_TILDA                          45
#define FTK_DOLLAR                         46
#define FTK_HASH                           47
#define FTK_UMINUS                         48
#define FTK_OPENPAR                        49
#define FTK_CLOSEPAR                       50
#define FTK_OPENBRA                        51
#define FTK_CLOSEBRA                       52
#define FTK_OPENSQB                        53
#define FTK_CLOSESQB                       54
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    flow_parserTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is flow_parserTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    flow_parserARG_SDECL     A static variable declaration for the %extra_argument
**    flow_parserARG_PDECL     A parameter declaration for the %extra_argument
**    flow_parserARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    flow_parserARG_STORE     Code to store %extra_argument into yypParser
**    flow_parserARG_FETCH     Code to extract %extra_argument from yypParser
**    flow_parserCTX_*         As flow_parserARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 76
#define YYACTIONTYPE unsigned short int
#define flow_parserTOKENTYPE int
typedef union {
  int yyinit;
  flow_parserTOKENTYPE yy0;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define flow_parserARG_SDECL  flow_ast *ast ;
#define flow_parserARG_PDECL , flow_ast *ast 
#define flow_parserARG_PARAM ,ast 
#define flow_parserARG_FETCH  flow_ast *ast =yypParser->ast ;
#define flow_parserARG_STORE yypParser->ast =ast ;
#define flow_parserCTX_SDECL
#define flow_parserCTX_PDECL
#define flow_parserCTX_PARAM
#define flow_parserCTX_FETCH
#define flow_parserCTX_STORE
#define YYNSTATE             96
#define YYNRULE              73
#define YYNRULE_WITH_ACTION  73
#define YYNTOKEN             55
#define YY_MAX_SHIFT         95
#define YY_MIN_SHIFTREDUCE   145
#define YY_MAX_SHIFTREDUCE   217
#define YY_ERROR_ACTION      218
#define YY_ACCEPT_ACTION     219
#define YY_NO_ACTION         220
#define YY_MIN_REDUCE        221
#define YY_MAX_REDUCE        293
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (593)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   257,  268,   85,   46,   51,   26,  257,   38,   85,   80,
 /*    10 */    54,   71,  255,  263,  259,  264,   39,   46,  255,  263,
 /*    20 */   253,  264,   70,   46,    5,    6,    7,  219,   44,   73,
 /*    30 */    12,   13,   10,   11,    8,    9,   14,  229,  252,   21,
 /*    40 */    18,   16,   17,   15,   21,   18,   16,   17,   15,  255,
 /*    50 */    27,   23,  174,  175,    4,    5,    6,    7,  226,   24,
 /*    60 */    91,   12,   13,   10,   11,    8,    9,   14,  216,  217,
 /*    70 */    21,   18,   16,   17,   15,    5,    6,    7,   16,   17,
 /*    80 */    15,   12,   13,   10,   11,    8,    9,   14,   37,   36,
 /*    90 */    21,   18,   16,   17,   15,   95,    5,    6,    7,   43,
 /*   100 */    76,  189,   12,   13,   10,   11,    8,    9,   14,   84,
 /*   110 */   156,   21,   18,   16,   17,   15,   24,    5,    6,    7,
 /*   120 */   221,   26,   48,   12,   13,   10,   11,    8,    9,   14,
 /*   130 */   247,   32,   21,   18,   16,   17,   15,   88,    7,   25,
 /*   140 */   214,   32,   12,   13,   10,   11,    8,    9,   14,  255,
 /*   150 */    42,   21,   18,   16,   17,   15,   79,  178,  174,  175,
 /*   160 */    12,   13,   10,   11,    8,    9,   14,  155,   47,   21,
 /*   170 */    18,   16,   17,   15,   40,  178,  174,  175,   10,   11,
 /*   180 */     8,    9,   14,   81,   89,   21,   18,   16,   17,   15,
 /*   190 */   260,   94,   31,   41,   37,   36,  255,  169,   93,   19,
 /*   200 */    83,   92,   34,  255,   22,  190,   79,  178,  174,  175,
 /*   210 */   255,  228,   37,   36,  154,  227,   75,   19,   83,   92,
 /*   220 */    34,  248,   22,  255,   79,  178,  174,  175,   90,   28,
 /*   230 */    69,  235,   77,  170,  216,  217,  236,   87,   86,   78,
 /*   240 */   255,  216,  217,   68,   37,   36,  259,   20,  168,   19,
 /*   250 */    83,   92,   34,  167,   22,   84,   45,  178,  174,  175,
 /*   260 */   213,   72,   37,   36,  259,   84,    2,   19,   83,   92,
 /*   270 */    34,  257,    1,   85,   47,   49,  191,   30,   29,  213,
 /*   280 */    82,  216,  217,  255,  263,   33,  264,  215,   46,  178,
 /*   290 */   174,  175,  165,   47,   37,   36,  214,  178,  174,  175,
 /*   300 */   164,   92,  163,  185,   35,  180,   32,  162,  257,  161,
 /*   310 */    85,  149,   56,  220,  148,  220,  220,  216,  217,  220,
 /*   320 */   255,  263,  166,  264,  220,   46,   37,   36,  220,  220,
 /*   330 */   220,  220,  220,   92,   37,   36,  257,  220,   85,  220,
 /*   340 */    50,   92,  220,  257,    3,   85,  220,   57,  255,  263,
 /*   350 */   220,  264,  220,   46,  220,  255,  263,  257,  264,   85,
 /*   360 */    46,   58,  220,  257,  220,   85,  220,   61,  220,  255,
 /*   370 */   263,  220,  264,  220,   46,  255,  263,  257,  264,   85,
 /*   380 */    46,   62,  220,  220,  257,  220,   85,  220,   63,  255,
 /*   390 */   263,  220,  264,  220,   46,  220,  255,  263,  220,  264,
 /*   400 */   257,   46,   85,  220,   64,  220,  257,  220,   85,  220,
 /*   410 */    59,  220,  255,  263,  220,  264,  220,   46,  255,  263,
 /*   420 */   257,  264,   85,   46,   60,  220,  257,  220,   85,  220,
 /*   430 */    65,  220,  255,  263,  220,  264,  220,   46,  255,  263,
 /*   440 */   257,  264,   85,   46,  274,  220,  220,  257,  220,   85,
 /*   450 */   220,  273,  255,  263,  220,  264,  220,   46,  220,  255,
 /*   460 */   263,  257,  264,   85,   46,  272,  220,  257,  220,   85,
 /*   470 */   220,   67,  220,  255,  263,  220,  264,  220,   46,  255,
 /*   480 */   263,  257,  264,   85,   46,  269,  220,  257,  220,   85,
 /*   490 */   220,   55,  220,  255,  263,  220,  264,  220,   46,  255,
 /*   500 */   263,  257,  264,   85,   46,   66,  220,  220,  257,  220,
 /*   510 */    85,  220,   51,  255,  263,  220,  264,  220,   46,  220,
 /*   520 */   255,  263,  257,  264,   85,   46,   53,  220,  257,  220,
 /*   530 */    85,  220,   52,  220,  255,  263,  220,  264,  220,   46,
 /*   540 */   255,  263,  220,  264,  220,   46,  220,  173,  178,   74,
 /*   550 */   175,   14,  220,  220,   21,   18,   16,   17,   15,  220,
 /*   560 */   220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
 /*   570 */   220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
 /*   580 */   220,  220,  220,  220,  220,   37,   36,  220,  220,  220,
 /*   590 */   220,  220,   92,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    58,   73,   60,   75,   62,    1,   58,    1,   60,    1,
 /*    10 */    62,   69,   70,   71,   72,   73,    1,   75,   70,   71,
 /*    20 */    70,   73,   74,   75,   24,   25,   26,   55,   56,   57,
 /*    30 */    30,   31,   32,   33,   34,   35,   36,   58,   70,   39,
 /*    40 */    40,   41,   42,   43,   39,   40,   41,   42,   43,   70,
 /*    50 */    50,   59,    3,    4,   23,   24,   25,   26,   61,    1,
 /*    60 */    65,   30,   31,   32,   33,   34,   35,   36,   22,   23,
 /*    70 */    39,   40,   41,   42,   43,   24,   25,   26,   41,   42,
 /*    80 */    43,   30,   31,   32,   33,   34,   35,   36,   39,   40,
 /*    90 */    39,   40,   41,   42,   43,   57,   24,   25,   26,   64,
 /*   100 */    65,   50,   30,   31,   32,   33,   34,   35,   36,   19,
 /*   110 */    52,   39,   40,   41,   42,   43,    1,   24,   25,   26,
 /*   120 */     0,    1,   50,   30,   31,   32,   33,   34,   35,   36,
 /*   130 */    61,   51,   39,   40,   41,   42,   43,   58,   26,   49,
 /*   140 */     1,   51,   30,   31,   32,   33,   34,   35,   36,   70,
 /*   150 */     1,   39,   40,   41,   42,   43,    1,    2,    3,    4,
 /*   160 */    30,   31,   32,   33,   34,   35,   36,   52,   21,   39,
 /*   170 */    40,   41,   42,   43,    1,    2,    3,    4,   32,   33,
 /*   180 */    34,   35,   36,   60,   58,   39,   40,   41,   42,   43,
 /*   190 */    72,   58,   59,   60,   39,   40,   70,   50,   58,   44,
 /*   200 */    45,   46,   47,   70,   49,   50,    1,    2,    3,    4,
 /*   210 */    70,   58,   39,   40,   18,   61,   63,   44,   45,   46,
 /*   220 */    47,   21,   49,   70,    1,    2,    3,    4,   58,   21,
 /*   230 */    60,   61,   20,   18,   22,   23,   66,   67,   68,   20,
 /*   240 */    70,   22,   23,   69,   39,   40,   72,   21,   50,   44,
 /*   250 */    45,   46,   47,   50,   49,   19,    1,    2,    3,    4,
 /*   260 */    20,   69,   39,   40,   72,   19,   49,   44,   45,   46,
 /*   270 */    47,   58,   49,   60,   21,   62,   50,   22,   23,   20,
 /*   280 */     1,   22,   23,   70,   71,   49,   73,    1,   75,    2,
 /*   290 */     3,    4,   18,   21,   39,   40,    1,    2,    3,    4,
 /*   300 */    18,   46,   18,   50,   49,    1,   51,   18,   58,   18,
 /*   310 */    60,   18,   62,   76,   18,   76,   76,   22,   23,   76,
 /*   320 */    70,   71,   50,   73,   76,   75,   39,   40,   76,   76,
 /*   330 */    76,   76,   76,   46,   39,   40,   58,   76,   60,   76,
 /*   340 */    62,   46,   76,   58,   49,   60,   76,   62,   70,   71,
 /*   350 */    76,   73,   76,   75,   76,   70,   71,   58,   73,   60,
 /*   360 */    75,   62,   76,   58,   76,   60,   76,   62,   76,   70,
 /*   370 */    71,   76,   73,   76,   75,   70,   71,   58,   73,   60,
 /*   380 */    75,   62,   76,   76,   58,   76,   60,   76,   62,   70,
 /*   390 */    71,   76,   73,   76,   75,   76,   70,   71,   76,   73,
 /*   400 */    58,   75,   60,   76,   62,   76,   58,   76,   60,   76,
 /*   410 */    62,   76,   70,   71,   76,   73,   76,   75,   70,   71,
 /*   420 */    58,   73,   60,   75,   62,   76,   58,   76,   60,   76,
 /*   430 */    62,   76,   70,   71,   76,   73,   76,   75,   70,   71,
 /*   440 */    58,   73,   60,   75,   62,   76,   76,   58,   76,   60,
 /*   450 */    76,   62,   70,   71,   76,   73,   76,   75,   76,   70,
 /*   460 */    71,   58,   73,   60,   75,   62,   76,   58,   76,   60,
 /*   470 */    76,   62,   76,   70,   71,   76,   73,   76,   75,   70,
 /*   480 */    71,   58,   73,   60,   75,   62,   76,   58,   76,   60,
 /*   490 */    76,   62,   76,   70,   71,   76,   73,   76,   75,   70,
 /*   500 */    71,   58,   73,   60,   75,   62,   76,   76,   58,   76,
 /*   510 */    60,   76,   62,   70,   71,   76,   73,   76,   75,   76,
 /*   520 */    70,   71,   58,   73,   60,   75,   62,   76,   58,   76,
 /*   530 */    60,   76,   62,   76,   70,   71,   76,   73,   76,   75,
 /*   540 */    70,   71,   76,   73,   76,   75,   76,    1,    2,    3,
 /*   550 */     4,   36,   76,   76,   39,   40,   41,   42,   43,   76,
 /*   560 */    76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
 /*   570 */    76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
 /*   580 */    76,   76,   76,   76,   76,   39,   40,   76,   76,   76,
 /*   590 */    76,   76,   46,   76,   76,   76,   76,   76,   76,   76,
 /*   600 */    76,   76,   76,   76,   76,   76,   76,   55,   55,   55,
 /*   610 */    55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
 /*   620 */    55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
 /*   630 */    55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
 /*   640 */    55,   55,   55,   55,   55,   55,   55,   55,
};
#define YY_SHIFT_COUNT    (95)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (546)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */     4,  173,  155,  205,  205,  205,  205,  205,  205,  205,
 /*    10 */   205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
 /*    20 */   205,  205,  205,  223,  255,  205,  295,  546,  287,  287,
 /*    30 */   287,  287,   58,    6,    8,   15,   49,   49,  212,  219,
 /*    40 */   259,   90,   46,  115,  120,   80,  139,  149,   80,    0,
 /*    50 */    31,   51,   72,   93,   93,   93,   93,  112,  130,  146,
 /*    60 */   146,  515,  515,  515,  515,    5,   37,   37,  147,  236,
 /*    70 */   226,  253,  272,  196,  200,  208,  215,  198,  203,  240,
 /*    80 */   240,  246,  217,  279,  286,  246,  274,  282,  284,  289,
 /*    90 */   291,  215,  304,  293,  296,  196,
};
#define YY_REDUCE_COUNT (48)
#define YY_REDUCE_MIN   (-72)
#define YY_REDUCE_MAX   (470)
static const short yy_reduce_ofst[] = {
 /*     0 */   -28,  -58,  -52,  213,  250,  278,  285,  299,  305,  319,
 /*    10 */   326,  342,  348,  362,  368,  382,  389,  403,  409,  423,
 /*    20 */   429,  443,  450,  464,  170,  470,  133,  153,  -21,   79,
 /*    30 */   126,  140,   35,  174,  -72,  192,  -50,  -32,   -8,   -8,
 /*    40 */    -8,   -3,   -8,   -5,   38,   69,  123,  118,  154,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
 /*    10 */   218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
 /*    20 */   218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
 /*    30 */   218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
 /*    40 */   290,  218,  218,  218,  218,  290,  287,  218,  218,  218,
 /*    50 */   218,  218,  218,  262,  285,  286,  284,  283,  282,  277,
 /*    60 */   276,  281,  280,  279,  278,  275,  270,  271,  218,  218,
 /*    70 */   218,  218,  218,  222,  250,  218,  233,  218,  218,  290,
 /*    80 */   218,  288,  218,  218,  218,  258,  218,  218,  218,  218,
 /*    90 */   218,  234,  218,  218,  218,  223,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  flow_parserARG_SDECL                /* A place to hold %extra_argument */
  flow_parserCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#ifndef NDEBUG
#include <stdio.h>
#include <assert.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void flow_parserTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "ID",
  /*    2 */ "STRING",
  /*    3 */ "INTEGER",
  /*    4 */ "FLOAT",
  /*    5 */ "SYMBOL",
  /*    6 */ "NODE",
  /*    7 */ "CONTAINER",
  /*    8 */ "ENTRY",
  /*    9 */ "IMPORT",
  /*   10 */ "DEFINE",
  /*   11 */ "OUTPUT",
  /*   12 */ "RETURN",
  /*   13 */ "ERROR",
  /*   14 */ "MOUNT",
  /*   15 */ "ENVIRONMENT",
  /*   16 */ "INPUT",
  /*   17 */ "HEADERS",
  /*   18 */ "SEMICOLON",
  /*   19 */ "DOT",
  /*   20 */ "AT",
  /*   21 */ "COMMA",
  /*   22 */ "EQUALS",
  /*   23 */ "COLON",
  /*   24 */ "QUESTION",
  /*   25 */ "OR",
  /*   26 */ "AND",
  /*   27 */ "BAR",
  /*   28 */ "CARET",
  /*   29 */ "AMP",
  /*   30 */ "NE",
  /*   31 */ "EQ",
  /*   32 */ "GT",
  /*   33 */ "LT",
  /*   34 */ "GE",
  /*   35 */ "LE",
  /*   36 */ "COMP",
  /*   37 */ "SHR",
  /*   38 */ "SHL",
  /*   39 */ "PLUS",
  /*   40 */ "MINUS",
  /*   41 */ "STAR",
  /*   42 */ "SLASH",
  /*   43 */ "PERCENT",
  /*   44 */ "BANG",
  /*   45 */ "TILDA",
  /*   46 */ "DOLLAR",
  /*   47 */ "HASH",
  /*   48 */ "UMINUS",
  /*   49 */ "OPENPAR",
  /*   50 */ "CLOSEPAR",
  /*   51 */ "OPENBRA",
  /*   52 */ "CLOSEBRA",
  /*   53 */ "OPENSQB",
  /*   54 */ "CLOSESQB",
  /*   55 */ "main",
  /*   56 */ "flow",
  /*   57 */ "stmt",
  /*   58 */ "valx",
  /*   59 */ "eqsc",
  /*   60 */ "dtid",
  /*   61 */ "blck",
  /*   62 */ "fldr",
  /*   63 */ "valc",
  /*   64 */ "list",
  /*   65 */ "elem",
  /*   66 */ "lblk",
  /*   67 */ "oexp",
  /*   68 */ "rexp",
  /*   69 */ "fldm",
  /*   70 */ "valn",
  /*   71 */ "vall",
  /*   72 */ "fldd",
  /*   73 */ "fldx",
  /*   74 */ "fldra",
  /*   75 */ "fldn",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "main ::= flow",
 /*   1 */ "flow ::= stmt",
 /*   2 */ "flow ::= flow stmt",
 /*   3 */ "stmt ::= ID valx SEMICOLON",
 /*   4 */ "stmt ::= ID eqsc valx SEMICOLON",
 /*   5 */ "stmt ::= ID dtid blck",
 /*   6 */ "stmt ::= ID dtid OPENPAR fldr CLOSEPAR blck",
 /*   7 */ "stmt ::= ID OPENPAR fldr CLOSEPAR valx",
 /*   8 */ "stmt ::= ID OPENPAR fldr CLOSEPAR valc COMMA valx",
 /*   9 */ "stmt ::= stmt SEMICOLON",
 /*  10 */ "blck ::= OPENBRA list CLOSEBRA",
 /*  11 */ "blck ::= OPENBRA CLOSEBRA",
 /*  12 */ "list ::= elem",
 /*  13 */ "list ::= list elem",
 /*  14 */ "elem ::= ID blck",
 /*  15 */ "elem ::= ID lblk",
 /*  16 */ "elem ::= ID valx SEMICOLON",
 /*  17 */ "elem ::= ID EQUALS valx SEMICOLON",
 /*  18 */ "elem ::= ID COLON valx SEMICOLON",
 /*  19 */ "elem ::= ID oexp SEMICOLON",
 /*  20 */ "elem ::= ID rexp SEMICOLON",
 /*  21 */ "rexp ::= OPENPAR fldm CLOSEPAR",
 /*  22 */ "rexp ::= OPENPAR ID AT CLOSEPAR",
 /*  23 */ "oexp ::= dtid OPENPAR ID AT CLOSEPAR",
 /*  24 */ "oexp ::= dtid OPENPAR fldm CLOSEPAR",
 /*  25 */ "elem ::= elem SEMICOLON",
 /*  26 */ "lblk ::= ID blck",
 /*  27 */ "valc ::= INTEGER",
 /*  28 */ "valc ::= ID",
 /*  29 */ "valn ::= INTEGER",
 /*  30 */ "valn ::= FLOAT",
 /*  31 */ "valn ::= PLUS valn",
 /*  32 */ "valn ::= MINUS valn",
 /*  33 */ "valx ::= STRING",
 /*  34 */ "valx ::= valn",
 /*  35 */ "valx ::= DOLLAR ID",
 /*  36 */ "vall ::= valx",
 /*  37 */ "vall ::= dtid",
 /*  38 */ "fldm ::= fldd",
 /*  39 */ "fldm ::= fldm COMMA fldd",
 /*  40 */ "fldd ::= ID eqsc OPENPAR fldm CLOSEPAR",
 /*  41 */ "fldd ::= ID eqsc fldr",
 /*  42 */ "fldr ::= vall",
 /*  43 */ "fldr ::= fldx",
 /*  44 */ "fldr ::= OPENPAR fldr CLOSEPAR",
 /*  45 */ "fldr ::= TILDA ID OPENPAR CLOSEPAR",
 /*  46 */ "fldr ::= TILDA ID OPENPAR fldra CLOSEPAR",
 /*  47 */ "fldr ::= HASH fldx",
 /*  48 */ "fldr ::= BANG fldr",
 /*  49 */ "fldr ::= fldr PLUS fldr",
 /*  50 */ "fldr ::= fldr MINUS fldr",
 /*  51 */ "fldr ::= fldr SLASH fldr",
 /*  52 */ "fldr ::= fldr STAR fldr",
 /*  53 */ "fldr ::= fldr PERCENT fldr",
 /*  54 */ "fldr ::= fldr COMP fldr",
 /*  55 */ "fldr ::= fldr EQ fldr",
 /*  56 */ "fldr ::= fldr NE fldr",
 /*  57 */ "fldr ::= fldr LT fldr",
 /*  58 */ "fldr ::= fldr GT fldr",
 /*  59 */ "fldr ::= fldr LE fldr",
 /*  60 */ "fldr ::= fldr GE fldr",
 /*  61 */ "fldr ::= fldr AND fldr",
 /*  62 */ "fldr ::= fldr OR fldr",
 /*  63 */ "fldr ::= fldr QUESTION fldr COLON fldr",
 /*  64 */ "fldra ::= fldr",
 /*  65 */ "fldra ::= fldra COMMA fldr",
 /*  66 */ "fldx ::= fldn",
 /*  67 */ "fldx ::= fldn dtid",
 /*  68 */ "fldn ::= ID AT",
 /*  69 */ "dtid ::= ID",
 /*  70 */ "dtid ::= dtid DOT ID",
 /*  71 */ "eqsc ::= EQUALS",
 /*  72 */ "eqsc ::= COLON",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to flow_parserAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void flow_parserInit(void *yypRawParser flow_parserCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  flow_parserCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef flow_parser_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to flow_parser and flow_parserFree.
*/
void *flow_parserAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) flow_parserCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    flow_parserCTX_STORE
    flow_parserInit(yypParser flow_parserCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* flow_parser_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  flow_parserARG_FETCH
  flow_parserCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void flow_parserFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef flow_parser_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void flow_parserFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  flow_parserFinalize(p);
  (*freeProc)(p);
}
#endif /* flow_parser_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int flow_parserStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int flow_parserCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   flow_parserARG_FETCH
   flow_parserCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   flow_parserARG_STORE /* Suppress warning about unused %extra_argument var */
   flow_parserCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  flow_parserTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    55,  /* (0) main ::= flow */
    56,  /* (1) flow ::= stmt */
    56,  /* (2) flow ::= flow stmt */
    57,  /* (3) stmt ::= ID valx SEMICOLON */
    57,  /* (4) stmt ::= ID eqsc valx SEMICOLON */
    57,  /* (5) stmt ::= ID dtid blck */
    57,  /* (6) stmt ::= ID dtid OPENPAR fldr CLOSEPAR blck */
    57,  /* (7) stmt ::= ID OPENPAR fldr CLOSEPAR valx */
    57,  /* (8) stmt ::= ID OPENPAR fldr CLOSEPAR valc COMMA valx */
    57,  /* (9) stmt ::= stmt SEMICOLON */
    61,  /* (10) blck ::= OPENBRA list CLOSEBRA */
    61,  /* (11) blck ::= OPENBRA CLOSEBRA */
    64,  /* (12) list ::= elem */
    64,  /* (13) list ::= list elem */
    65,  /* (14) elem ::= ID blck */
    65,  /* (15) elem ::= ID lblk */
    65,  /* (16) elem ::= ID valx SEMICOLON */
    65,  /* (17) elem ::= ID EQUALS valx SEMICOLON */
    65,  /* (18) elem ::= ID COLON valx SEMICOLON */
    65,  /* (19) elem ::= ID oexp SEMICOLON */
    65,  /* (20) elem ::= ID rexp SEMICOLON */
    68,  /* (21) rexp ::= OPENPAR fldm CLOSEPAR */
    68,  /* (22) rexp ::= OPENPAR ID AT CLOSEPAR */
    67,  /* (23) oexp ::= dtid OPENPAR ID AT CLOSEPAR */
    67,  /* (24) oexp ::= dtid OPENPAR fldm CLOSEPAR */
    65,  /* (25) elem ::= elem SEMICOLON */
    66,  /* (26) lblk ::= ID blck */
    63,  /* (27) valc ::= INTEGER */
    63,  /* (28) valc ::= ID */
    70,  /* (29) valn ::= INTEGER */
    70,  /* (30) valn ::= FLOAT */
    70,  /* (31) valn ::= PLUS valn */
    70,  /* (32) valn ::= MINUS valn */
    58,  /* (33) valx ::= STRING */
    58,  /* (34) valx ::= valn */
    58,  /* (35) valx ::= DOLLAR ID */
    71,  /* (36) vall ::= valx */
    71,  /* (37) vall ::= dtid */
    69,  /* (38) fldm ::= fldd */
    69,  /* (39) fldm ::= fldm COMMA fldd */
    72,  /* (40) fldd ::= ID eqsc OPENPAR fldm CLOSEPAR */
    72,  /* (41) fldd ::= ID eqsc fldr */
    62,  /* (42) fldr ::= vall */
    62,  /* (43) fldr ::= fldx */
    62,  /* (44) fldr ::= OPENPAR fldr CLOSEPAR */
    62,  /* (45) fldr ::= TILDA ID OPENPAR CLOSEPAR */
    62,  /* (46) fldr ::= TILDA ID OPENPAR fldra CLOSEPAR */
    62,  /* (47) fldr ::= HASH fldx */
    62,  /* (48) fldr ::= BANG fldr */
    62,  /* (49) fldr ::= fldr PLUS fldr */
    62,  /* (50) fldr ::= fldr MINUS fldr */
    62,  /* (51) fldr ::= fldr SLASH fldr */
    62,  /* (52) fldr ::= fldr STAR fldr */
    62,  /* (53) fldr ::= fldr PERCENT fldr */
    62,  /* (54) fldr ::= fldr COMP fldr */
    62,  /* (55) fldr ::= fldr EQ fldr */
    62,  /* (56) fldr ::= fldr NE fldr */
    62,  /* (57) fldr ::= fldr LT fldr */
    62,  /* (58) fldr ::= fldr GT fldr */
    62,  /* (59) fldr ::= fldr LE fldr */
    62,  /* (60) fldr ::= fldr GE fldr */
    62,  /* (61) fldr ::= fldr AND fldr */
    62,  /* (62) fldr ::= fldr OR fldr */
    62,  /* (63) fldr ::= fldr QUESTION fldr COLON fldr */
    74,  /* (64) fldra ::= fldr */
    74,  /* (65) fldra ::= fldra COMMA fldr */
    73,  /* (66) fldx ::= fldn */
    73,  /* (67) fldx ::= fldn dtid */
    75,  /* (68) fldn ::= ID AT */
    60,  /* (69) dtid ::= ID */
    60,  /* (70) dtid ::= dtid DOT ID */
    59,  /* (71) eqsc ::= EQUALS */
    59,  /* (72) eqsc ::= COLON */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) main ::= flow */
   -1,  /* (1) flow ::= stmt */
   -2,  /* (2) flow ::= flow stmt */
   -3,  /* (3) stmt ::= ID valx SEMICOLON */
   -4,  /* (4) stmt ::= ID eqsc valx SEMICOLON */
   -3,  /* (5) stmt ::= ID dtid blck */
   -6,  /* (6) stmt ::= ID dtid OPENPAR fldr CLOSEPAR blck */
   -5,  /* (7) stmt ::= ID OPENPAR fldr CLOSEPAR valx */
   -7,  /* (8) stmt ::= ID OPENPAR fldr CLOSEPAR valc COMMA valx */
   -2,  /* (9) stmt ::= stmt SEMICOLON */
   -3,  /* (10) blck ::= OPENBRA list CLOSEBRA */
   -2,  /* (11) blck ::= OPENBRA CLOSEBRA */
   -1,  /* (12) list ::= elem */
   -2,  /* (13) list ::= list elem */
   -2,  /* (14) elem ::= ID blck */
   -2,  /* (15) elem ::= ID lblk */
   -3,  /* (16) elem ::= ID valx SEMICOLON */
   -4,  /* (17) elem ::= ID EQUALS valx SEMICOLON */
   -4,  /* (18) elem ::= ID COLON valx SEMICOLON */
   -3,  /* (19) elem ::= ID oexp SEMICOLON */
   -3,  /* (20) elem ::= ID rexp SEMICOLON */
   -3,  /* (21) rexp ::= OPENPAR fldm CLOSEPAR */
   -4,  /* (22) rexp ::= OPENPAR ID AT CLOSEPAR */
   -5,  /* (23) oexp ::= dtid OPENPAR ID AT CLOSEPAR */
   -4,  /* (24) oexp ::= dtid OPENPAR fldm CLOSEPAR */
   -2,  /* (25) elem ::= elem SEMICOLON */
   -2,  /* (26) lblk ::= ID blck */
   -1,  /* (27) valc ::= INTEGER */
   -1,  /* (28) valc ::= ID */
   -1,  /* (29) valn ::= INTEGER */
   -1,  /* (30) valn ::= FLOAT */
   -2,  /* (31) valn ::= PLUS valn */
   -2,  /* (32) valn ::= MINUS valn */
   -1,  /* (33) valx ::= STRING */
   -1,  /* (34) valx ::= valn */
   -2,  /* (35) valx ::= DOLLAR ID */
   -1,  /* (36) vall ::= valx */
   -1,  /* (37) vall ::= dtid */
   -1,  /* (38) fldm ::= fldd */
   -3,  /* (39) fldm ::= fldm COMMA fldd */
   -5,  /* (40) fldd ::= ID eqsc OPENPAR fldm CLOSEPAR */
   -3,  /* (41) fldd ::= ID eqsc fldr */
   -1,  /* (42) fldr ::= vall */
   -1,  /* (43) fldr ::= fldx */
   -3,  /* (44) fldr ::= OPENPAR fldr CLOSEPAR */
   -4,  /* (45) fldr ::= TILDA ID OPENPAR CLOSEPAR */
   -5,  /* (46) fldr ::= TILDA ID OPENPAR fldra CLOSEPAR */
   -2,  /* (47) fldr ::= HASH fldx */
   -2,  /* (48) fldr ::= BANG fldr */
   -3,  /* (49) fldr ::= fldr PLUS fldr */
   -3,  /* (50) fldr ::= fldr MINUS fldr */
   -3,  /* (51) fldr ::= fldr SLASH fldr */
   -3,  /* (52) fldr ::= fldr STAR fldr */
   -3,  /* (53) fldr ::= fldr PERCENT fldr */
   -3,  /* (54) fldr ::= fldr COMP fldr */
   -3,  /* (55) fldr ::= fldr EQ fldr */
   -3,  /* (56) fldr ::= fldr NE fldr */
   -3,  /* (57) fldr ::= fldr LT fldr */
   -3,  /* (58) fldr ::= fldr GT fldr */
   -3,  /* (59) fldr ::= fldr LE fldr */
   -3,  /* (60) fldr ::= fldr GE fldr */
   -3,  /* (61) fldr ::= fldr AND fldr */
   -3,  /* (62) fldr ::= fldr OR fldr */
   -5,  /* (63) fldr ::= fldr QUESTION fldr COLON fldr */
   -1,  /* (64) fldra ::= fldr */
   -3,  /* (65) fldra ::= fldra COMMA fldr */
   -1,  /* (66) fldx ::= fldn */
   -2,  /* (67) fldx ::= fldn dtid */
   -2,  /* (68) fldn ::= ID AT */
   -1,  /* (69) dtid ::= ID */
   -3,  /* (70) dtid ::= dtid DOT ID */
   -1,  /* (71) eqsc ::= EQUALS */
   -1,  /* (72) eqsc ::= COLON */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  flow_parserTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  flow_parserCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  flow_parserARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* main ::= flow */
#line 46 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_ACCEPT, yymsp[0].minor.yy0); }
#line 1284 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 1: /* flow ::= stmt */
#line 48 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_flow, yymsp[0].minor.yy0); }
#line 1290 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 2: /* flow ::= flow stmt */
      case 13: /* list ::= list elem */ yytestcase(yyruleno==13);
#line 49 "flow-parser.y"
{ yylhsminor.yy0 = ast->nappend(yymsp[-1].minor.yy0, yymsp[0].minor.yy0); }
#line 1297 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 3: /* stmt ::= ID valx SEMICOLON */
#line 51 "flow-parser.y"
{ yylhsminor.yy0 = ast->stmt_keyw(yymsp[-2].minor.yy0) == FTK_IMPORT? ast->node(FTK_IMPORT, yymsp[-1].minor.yy0): ast->node(ast->stmt_keyw(yymsp[-2].minor.yy0), yymsp[-2].minor.yy0, yymsp[-1].minor.yy0); 
                                                                 ast->expect(yylhsminor.yy0, {FTK_DEFINE, FTK_IMPORT}, "import directive or variable definition expected"); 
                                                                 if(ast->stmt_keyw(yymsp[-2].minor.yy0) == FTK_DEFINE) ast->define_var(ast->get_id(yymsp[-2].minor.yy0), yymsp[-1].minor.yy0);
                                                               }
#line 1306 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 4: /* stmt ::= ID eqsc valx SEMICOLON */
#line 55 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(ast->stmt_keyw(yymsp[-3].minor.yy0), yymsp[-3].minor.yy0, yymsp[-1].minor.yy0); ast->expect(yylhsminor.yy0, FTK_DEFINE, "keyword used as variable name");
                                                                 ast->define_var(ast->get_id(yymsp[-3].minor.yy0), yymsp[-1].minor.yy0);
                                                               }
#line 1314 "flow-parser.c"
  yymsp[-3].minor.yy0 = yylhsminor.yy0;
        break;
      case 5: /* stmt ::= ID dtid blck */
#line 59 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(ast->stmt_keyw(yymsp[-2].minor.yy0), yymsp[-2].minor.yy0, yymsp[-1].minor.yy0, yymsp[0].minor.yy0); 
                                                                 ast->expect(yylhsminor.yy0, {FTK_CONTAINER, FTK_NODE, FTK_ENTRY}, "expected \"node\", \"entry\" or \"container\" here");
                                                                 if(ast->at(yylhsminor.yy0).type == FTK_NODE || ast->at(yylhsminor.yy0).type == FTK_CONTAINER) {
                                                                     ast->name.put(yylhsminor.yy0, ast->get_dotted_id(yymsp[-1].minor.yy0));
                                                                     ast->type.put(yylhsminor.yy0, ast->get_dotted_id(yymsp[-1].minor.yy0, 0, 1)); 
                                                                 } else {
                                                                     ast->name.put(yylhsminor.yy0, ast->get_dotted_id(yymsp[-1].minor.yy0));
                                                                 }
                                                                 ast->type.put(yymsp[0].minor.yy0, ast->get_id(yymsp[-2].minor.yy0));
                                                               }
#line 1329 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 6: /* stmt ::= ID dtid OPENPAR fldr CLOSEPAR blck */
#line 70 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(ast->stmt_keyw(yymsp[-5].minor.yy0), yymsp[-5].minor.yy0, yymsp[-4].minor.yy0, yymsp[0].minor.yy0, yymsp[-2].minor.yy0); 
                                                                 ast->expect(yylhsminor.yy0, FTK_NODE, "expected \"node\" keyword"); 
                                                                 ast->type.put(yylhsminor.yy0, ast->get_dotted_id(yymsp[-4].minor.yy0, 0, 1)); 
                                                                 ast->name.put(yylhsminor.yy0, ast->get_dotted_id(yymsp[-4].minor.yy0));
                                                                 ast->type.put(yymsp[0].minor.yy0, ast->get_id(yymsp[-5].minor.yy0));
                                                               }
#line 1340 "flow-parser.c"
  yymsp[-5].minor.yy0 = yylhsminor.yy0;
        break;
      case 7: /* stmt ::= ID OPENPAR fldr CLOSEPAR valx */
#line 77 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(ast->stmt_keyw(yymsp[-4].minor.yy0), yymsp[-2].minor.yy0, yymsp[0].minor.yy0);
                                                                 ast->expect(yylhsminor.yy0, FTK_ERROR, "expected \"error\" keyword");  
                                                               }
#line 1348 "flow-parser.c"
  yymsp[-4].minor.yy0 = yylhsminor.yy0;
        break;
      case 8: /* stmt ::= ID OPENPAR fldr CLOSEPAR valc COMMA valx */
#line 80 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(ast->stmt_keyw(yymsp[-6].minor.yy0), yymsp[-4].minor.yy0, yymsp[-2].minor.yy0, yymsp[0].minor.yy0);
                                                                 ast->expect(yylhsminor.yy0, FTK_ERROR, "expected \"error\" keyword");  
                                                                 ast->expect(yymsp[-2].minor.yy0, {FTK_INTEGER, FTK_ID}, "expected integer or label");
                                                               }
#line 1357 "flow-parser.c"
  yymsp[-6].minor.yy0 = yylhsminor.yy0;
        break;
      case 9: /* stmt ::= stmt SEMICOLON */
      case 25: /* elem ::= elem SEMICOLON */ yytestcase(yyruleno==25);
      case 68: /* fldn ::= ID AT */ yytestcase(yyruleno==68);
#line 84 "flow-parser.y"
{ yylhsminor.yy0 = yymsp[-1].minor.yy0; }
#line 1365 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 10: /* blck ::= OPENBRA list CLOSEBRA */
      case 44: /* fldr ::= OPENPAR fldr CLOSEPAR */ yytestcase(yyruleno==44);
#line 88 "flow-parser.y"
{ yymsp[-2].minor.yy0 = yymsp[-1].minor.yy0; }
#line 1372 "flow-parser.c"
        break;
      case 11: /* blck ::= OPENBRA CLOSEBRA */
#line 89 "flow-parser.y"
{ yylhsminor.yy0 = ast->chtype(yymsp[-1].minor.yy0, FTK_blck); }
#line 1377 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 12: /* list ::= elem */
#line 93 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_blck, yymsp[0].minor.yy0); }
#line 1383 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 14: /* elem ::= ID blck */
#line 99 "flow-parser.y"
{ ast->chtype(yymsp[0].minor.yy0, ast->blck_keyw(yymsp[-1].minor.yy0));
                                                                 if(ast->at(yymsp[0].minor.yy0).type == FTK_MOUNT) {
                                                                    yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-1].minor.yy0, ast->node(FTK_MOUNT, yymsp[0].minor.yy0));
                                                                    ast->chtype(yymsp[0].minor.yy0, FTK_blck);
                                                                 } else {
                                                                    yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-1].minor.yy0, yymsp[0].minor.yy0);
                                                                 }
                                                                 ast->expect(yymsp[0].minor.yy0, {FTK_HEADERS, FTK_ENVIRONMENT, FTK_MOUNT, FTK_blck}, "expected \"headers\", \"environment\", or \"mount\" here"); 

                                                               }
#line 1398 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 15: /* elem ::= ID lblk */
#line 109 "flow-parser.y"
{ ast->chtype(yymsp[0].minor.yy0, ast->blck_keyw(yymsp[-1].minor.yy0));
                                                                 yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-1].minor.yy0, yymsp[0].minor.yy0); 
                                                                 ast->expect(yymsp[0].minor.yy0, {FTK_MOUNT, FTK_lblk}, "expected \"mount\" here"); 
                                                               }
#line 1407 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 16: /* elem ::= ID valx SEMICOLON */
#line 113 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-2].minor.yy0, yymsp[-1].minor.yy0); }
#line 1413 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 17: /* elem ::= ID EQUALS valx SEMICOLON */
      case 18: /* elem ::= ID COLON valx SEMICOLON */ yytestcase(yyruleno==18);
      case 24: /* oexp ::= dtid OPENPAR fldm CLOSEPAR */ yytestcase(yyruleno==24);
#line 114 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-3].minor.yy0, yymsp[-1].minor.yy0); }
#line 1421 "flow-parser.c"
  yymsp[-3].minor.yy0 = yylhsminor.yy0;
        break;
      case 19: /* elem ::= ID oexp SEMICOLON */
#line 116 "flow-parser.y"
{ ast->chtype(yymsp[-1].minor.yy0, ast->blck_keyw(yymsp[-2].minor.yy0));
                                                                 yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-2].minor.yy0, yymsp[-1].minor.yy0);
                                                                 ast->expect(yymsp[-1].minor.yy0, {FTK_RETURN, FTK_OUTPUT}, "expected \"output\" or \"return\" here"); 
                                                               }
#line 1430 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 20: /* elem ::= ID rexp SEMICOLON */
#line 120 "flow-parser.y"
{ ast->chtype(yymsp[-1].minor.yy0, ast->blck_keyw(yymsp[-2].minor.yy0));
                                                                 yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-2].minor.yy0, yymsp[-1].minor.yy0); 
                                                                 ast->expect(yymsp[-1].minor.yy0, FTK_RETURN, "expected \"return\" keyword here"); 
                                                               }
#line 1439 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 21: /* rexp ::= OPENPAR fldm CLOSEPAR */
#line 124 "flow-parser.y"
{ yymsp[-2].minor.yy0 = ast->node(FTK_elem, yymsp[-1].minor.yy0); }
#line 1445 "flow-parser.c"
        break;
      case 22: /* rexp ::= OPENPAR ID AT CLOSEPAR */
#line 125 "flow-parser.y"
{ yymsp[-3].minor.yy0 = ast->node(FTK_elem, ast->node(FTK_fldx, yymsp[-2].minor.yy0)); }
#line 1450 "flow-parser.c"
        break;
      case 23: /* oexp ::= dtid OPENPAR ID AT CLOSEPAR */
#line 126 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-4].minor.yy0, ast->node(FTK_fldx, yymsp[-2].minor.yy0)); }
#line 1455 "flow-parser.c"
  yymsp[-4].minor.yy0 = yylhsminor.yy0;
        break;
      case 26: /* lblk ::= ID blck */
#line 131 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_lblk, yymsp[-1].minor.yy0, yymsp[0].minor.yy0); ast->name.put(yylhsminor.yy0, ast->get_id(yymsp[-1].minor.yy0)); }
#line 1461 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 27: /* valc ::= INTEGER */
      case 28: /* valc ::= ID */ yytestcase(yyruleno==28);
      case 29: /* valn ::= INTEGER */ yytestcase(yyruleno==29);
      case 30: /* valn ::= FLOAT */ yytestcase(yyruleno==30);
      case 33: /* valx ::= STRING */ yytestcase(yyruleno==33);
      case 34: /* valx ::= valn */ yytestcase(yyruleno==34);
      case 36: /* vall ::= valx */ yytestcase(yyruleno==36);
      case 42: /* fldr ::= vall */ yytestcase(yyruleno==42);
      case 43: /* fldr ::= fldx */ yytestcase(yyruleno==43);
      case 66: /* fldx ::= fldn */ yytestcase(yyruleno==66);
#line 134 "flow-parser.y"
{ yylhsminor.yy0 = yymsp[0].minor.yy0; }
#line 1476 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 31: /* valn ::= PLUS valn */
#line 140 "flow-parser.y"
{ yymsp[-1].minor.yy0 = yymsp[0].minor.yy0; }
#line 1482 "flow-parser.c"
        break;
      case 32: /* valn ::= MINUS valn */
#line 141 "flow-parser.y"
{ yymsp[-1].minor.yy0 = ast->negate(yymsp[0].minor.yy0); }
#line 1487 "flow-parser.c"
        break;
      case 35: /* valx ::= DOLLAR ID */
#line 147 "flow-parser.y"
{ yymsp[-1].minor.yy0 = ast->lookup_var(ast->get_id(yymsp[0].minor.yy0)); if(yymsp[-1].minor.yy0 == 0) ast->error(yymsp[0].minor.yy0, stru1::sfmt() << "reference to undefined symbol \"" << ast->get_id(yymsp[-1].minor.yy0=yymsp[0].minor.yy0) << "\""); }
#line 1492 "flow-parser.c"
        break;
      case 37: /* vall ::= dtid */
#line 152 "flow-parser.y"
{ yylhsminor.yy0 = ast->chtype(yymsp[0].minor.yy0, FTK_enum); }
#line 1497 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 38: /* fldm ::= fldd */
#line 155 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldm, yymsp[0].minor.yy0); }
#line 1503 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 39: /* fldm ::= fldm COMMA fldd */
      case 65: /* fldra ::= fldra COMMA fldr */ yytestcase(yyruleno==65);
      case 70: /* dtid ::= dtid DOT ID */ yytestcase(yyruleno==70);
#line 156 "flow-parser.y"
{ yylhsminor.yy0 = ast->nappend(yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1511 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 40: /* fldd ::= ID eqsc OPENPAR fldm CLOSEPAR */
#line 160 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldd, yymsp[-4].minor.yy0, yymsp[-1].minor.yy0); ast->chinteger(yylhsminor.yy0, ast->at(yymsp[-3].minor.yy0).token.integer_value); }
#line 1517 "flow-parser.c"
  yymsp[-4].minor.yy0 = yylhsminor.yy0;
        break;
      case 41: /* fldd ::= ID eqsc fldr */
#line 161 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldd, yymsp[-2].minor.yy0, yymsp[0].minor.yy0); ast->chinteger(yylhsminor.yy0, ast->at(yymsp[-1].minor.yy0).token.integer_value); }
#line 1523 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 45: /* fldr ::= TILDA ID OPENPAR CLOSEPAR */
#line 168 "flow-parser.y"
{ yymsp[-3].minor.yy0 = ast->node(FTK_fldr, yymsp[-2].minor.yy0); }
#line 1529 "flow-parser.c"
        break;
      case 46: /* fldr ::= TILDA ID OPENPAR fldra CLOSEPAR */
#line 169 "flow-parser.y"
{ yymsp[-4].minor.yy0 = ast->nprepend(yymsp[-1].minor.yy0, yymsp[-3].minor.yy0); }
#line 1534 "flow-parser.c"
        break;
      case 47: /* fldr ::= HASH fldx */
      case 48: /* fldr ::= BANG fldr */ yytestcase(yyruleno==48);
#line 170 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldr, yymsp[-1].minor.yy0, yymsp[0].minor.yy0); }
#line 1540 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 49: /* fldr ::= fldr PLUS fldr */
      case 50: /* fldr ::= fldr MINUS fldr */ yytestcase(yyruleno==50);
      case 51: /* fldr ::= fldr SLASH fldr */ yytestcase(yyruleno==51);
      case 52: /* fldr ::= fldr STAR fldr */ yytestcase(yyruleno==52);
      case 53: /* fldr ::= fldr PERCENT fldr */ yytestcase(yyruleno==53);
      case 54: /* fldr ::= fldr COMP fldr */ yytestcase(yyruleno==54);
      case 55: /* fldr ::= fldr EQ fldr */ yytestcase(yyruleno==55);
      case 56: /* fldr ::= fldr NE fldr */ yytestcase(yyruleno==56);
      case 57: /* fldr ::= fldr LT fldr */ yytestcase(yyruleno==57);
      case 58: /* fldr ::= fldr GT fldr */ yytestcase(yyruleno==58);
      case 59: /* fldr ::= fldr LE fldr */ yytestcase(yyruleno==59);
      case 60: /* fldr ::= fldr GE fldr */ yytestcase(yyruleno==60);
      case 61: /* fldr ::= fldr AND fldr */ yytestcase(yyruleno==61);
      case 62: /* fldr ::= fldr OR fldr */ yytestcase(yyruleno==62);
#line 172 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldr, yymsp[-1].minor.yy0, yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1559 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 63: /* fldr ::= fldr QUESTION fldr COLON fldr */
#line 186 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldr, yymsp[-3].minor.yy0, yymsp[-4].minor.yy0, yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1565 "flow-parser.c"
  yymsp[-4].minor.yy0 = yylhsminor.yy0;
        break;
      case 64: /* fldra ::= fldr */
#line 188 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldr, yymsp[0].minor.yy0); }
#line 1571 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 67: /* fldx ::= fldn dtid */
#line 194 "flow-parser.y"
{ yylhsminor.yy0 = ast->chtype(ast->nprepend(yymsp[0].minor.yy0, yymsp[-1].minor.yy0), FTK_fldx); }
#line 1577 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 69: /* dtid ::= ID */
#line 202 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_dtid, yymsp[0].minor.yy0); }
#line 1583 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 71: /* eqsc ::= EQUALS */
      case 72: /* eqsc ::= COLON */ yytestcase(yyruleno==72);
#line 207 "flow-parser.y"
{ ast->chinteger(yymsp[0].minor.yy0, 0); }
#line 1590 "flow-parser.c"
        break;
      default:
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  flow_parserARG_FETCH
  flow_parserCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 42 "flow-parser.y"

    ast->node(FTK_SYNTAX_ERROR, (int) ast->store.size());
#line 1637 "flow-parser.c"
/************ End %parse_failure code *****************************************/
  flow_parserARG_STORE /* Suppress warning about unused %extra_argument variable */
  flow_parserCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  flow_parserTOKENTYPE yyminor         /* The minor type of the error token */
){
  flow_parserARG_FETCH
  flow_parserCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 36 "flow-parser.y"

    ast->node(FTK_SYNTAX_ERROR, (int) ast->store.size());
#line 1659 "flow-parser.c"
/************ End %syntax_error code ******************************************/
  flow_parserARG_STORE /* Suppress warning about unused %extra_argument variable */
  flow_parserCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  flow_parserARG_FETCH
  flow_parserCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
#line 39 "flow-parser.y"

    //std::cerr << "parsed just fine, ast size: " << ast->store.size() << " root: " << ast->store.back().children[0] << "\n";
#line 1688 "flow-parser.c"
/*********** End %parse_accept code *******************************************/
  flow_parserARG_STORE /* Suppress warning about unused %extra_argument variable */
  flow_parserCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "flow_parserAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void flow_parser(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  flow_parserTOKENTYPE yyminor       /* The value for the token */
  flow_parserARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  flow_parserCTX_FETCH
  flow_parserARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
#ifndef NDEBUG
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
#if YYSTACKDEPTH>0 
        if( yypParser->yytos>=yypParser->yystackEnd ){
          yyStackOverflow(yypParser);
          break;
        }
#else
        if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
#endif
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor flow_parserCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos >= yypParser->yystack
            && (yyact = yy_find_reduce_action(
                        yypParser->yytos->stateno,
                        YYERRORSYMBOL)) > YY_MAX_SHIFTREDUCE
        ){
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos < yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int flow_parserFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
