/* This file is automatically generated by Lemon from input grammar
** source file "flow-parser.y". */
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 37 "flow-parser.y"

#include "flow-comp.H"
#define YYNOERRORRECOVERY
#line 33 "flow-parser.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef FTK_ID
#define FTK_ID                              1
#define FTK_STRING                          2
#define FTK_INTEGER                         3
#define FTK_FLOAT                           4
#define FTK_URL                             5
#define FTK_NODE                            6
#define FTK_CONTAINER                       7
#define FTK_ENTRY                           8
#define FTK_IMPORT                          9
#define FTK_INPUT                          10
#define FTK_OUTPUT                         11
#define FTK_RETURN                         12
#define FTK_ERROR                          13
#define FTK_INCLUDE                        14
#define FTK_MOUNT                          15
#define FTK_ENVIRONMENT                    16
#define FTK_HEADER                         17
#define FTK_INIT                           18
#define FTK_LIMITS                         19
#define FTK_REPO                           20
#define FTK_CPU                            21
#define FTK_GPU                            22
#define FTK_MEMORY                         23
#define FTK_MBU                            24
#define FTK_SEMICOLON                      25
#define FTK_DOT                            26
#define FTK_AT                             27
#define FTK_COMMA                          28
#define FTK_EQUALS                         29
#define FTK_COLON                          30
#define FTK_QUESTION                       31
#define FTK_OR                             32
#define FTK_AND                            33
#define FTK_BAR                            34
#define FTK_CARET                          35
#define FTK_AMP                            36
#define FTK_NE                             37
#define FTK_EQ                             38
#define FTK_GT                             39
#define FTK_LT                             40
#define FTK_GE                             41
#define FTK_LE                             42
#define FTK_COMP                           43
#define FTK_SHR                            44
#define FTK_SHL                            45
#define FTK_PLUS                           46
#define FTK_MINUS                          47
#define FTK_STAR                           48
#define FTK_SLASH                          49
#define FTK_PERCENT                        50
#define FTK_POW                            51
#define FTK_BANG                           52
#define FTK_TILDA                          53
#define FTK_DOLLAR                         54
#define FTK_HASH                           55
#define FTK_OPENPAR                        56
#define FTK_CLOSEPAR                       57
#define FTK_OPENBRA                        58
#define FTK_CLOSEBRA                       59
#define FTK_OPENSQB                        60
#define FTK_CLOSESQB                       61
#define FTK_ANY                            62
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    flow_parserTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is flow_parserTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    flow_parserARG_SDECL     A static variable declaration for the %extra_argument
**    flow_parserARG_PDECL     A parameter declaration for the %extra_argument
**    flow_parserARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    flow_parserARG_STORE     Code to store %extra_argument into yypParser
**    flow_parserARG_FETCH     Code to extract %extra_argument from yypParser
**    flow_parserCTX_*         As flow_parserARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 84
#define YYACTIONTYPE unsigned short int
#define YYWILDCARD 62
#define flow_parserTOKENTYPE int
typedef union {
  int yyinit;
  flow_parserTOKENTYPE yy0;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define flow_parserARG_SDECL  struct fc::compiler *ast ;
#define flow_parserARG_PDECL , struct fc::compiler *ast 
#define flow_parserARG_PARAM ,ast 
#define flow_parserARG_FETCH  struct fc::compiler *ast =yypParser->ast ;
#define flow_parserARG_STORE yypParser->ast =ast ;
#define flow_parserCTX_SDECL
#define flow_parserCTX_PDECL
#define flow_parserCTX_PARAM
#define flow_parserCTX_FETCH
#define flow_parserCTX_STORE
#define YYFALLBACK 1
#define YYNSTATE             102
#define YYNRULE              77
#define YYNRULE_WITH_ACTION  77
#define YYNTOKEN             63
#define YY_MAX_SHIFT         101
#define YY_MIN_SHIFTREDUCE   152
#define YY_MAX_SHIFTREDUCE   228
#define YY_ERROR_ACTION      229
#define YY_ACCEPT_ACTION     230
#define YY_NO_ACTION         231
#define YY_MIN_REDUCE        232
#define YY_MAX_REDUCE        308
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (616)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   272,  268,   26,   90,   53,   39,  272,   28,   93,   90,
 /*    10 */    58,   76,  270,  279,  274,  280,   85,   48,  270,  279,
 /*    20 */   270,  280,   75,   48,  100,   32,  238,   42,  230,   46,
 /*    30 */    78,    7,    8,    9,   44,   81,  270,   14,   15,   12,
 /*    40 */    13,   10,   11,   16,  185,  186,   23,   20,   18,   19,
 /*    50 */    17,   23,   20,   18,   19,   17,   82,    3,  227,  228,
 /*    60 */   165,  180,    6,    7,    8,    9,   18,   19,   17,   14,
 /*    70 */    15,   12,   13,   10,   11,   16,  227,  228,   23,   20,
 /*    80 */    18,   19,   17,   83,   25,  227,  228,   38,   37,    7,
 /*    90 */     8,    9,  284,  239,   48,   14,   15,   12,   13,   10,
 /*   100 */    11,   16,  232,   28,   23,   20,   18,   19,   17,  267,
 /*   110 */     7,    8,    9,  224,  264,  201,   14,   15,   12,   13,
 /*   120 */    10,   11,   16,   94,   49,   23,   20,   18,   19,   17,
 /*   130 */    31,    7,    8,    9,   26,  270,   50,   14,   15,   12,
 /*   140 */    13,   10,   11,   16,   96,   40,   23,   20,   18,   19,
 /*   150 */    17,    9,   22,  179,  101,   14,   15,   12,   13,   10,
 /*   160 */    11,   16,   35,  262,   23,   20,   18,   19,   17,   84,
 /*   170 */   189,  185,  186,  225,   14,   15,   12,   13,   10,   11,
 /*   180 */    16,  203,   97,   23,   20,   18,   19,   17,   41,  189,
 /*   190 */   185,  186,  164,   43,  270,   12,   13,   10,   11,   16,
 /*   200 */    99,  177,   23,   20,   18,   19,   17,   89,  189,  185,
 /*   210 */   186,   86,  270,  240,   38,   37,   72,  189,   79,  186,
 /*   220 */    21,   88,   98,   36,   24,  202,  276,   84,  189,  185,
 /*   230 */   186,  263,    4,   38,   37,   73,  163,   33,  274,   21,
 /*   240 */    88,   98,   36,   24,   84,  189,  185,  186,   47,  189,
 /*   250 */   185,  186,   38,   37,  181,  224,   89,  227,  228,  178,
 /*   260 */    98,   38,   37,   45,  189,  185,  186,   21,   88,   98,
 /*   270 */    36,   24,   38,   37,  176,  224,   30,   29,   21,   88,
 /*   280 */    98,   36,   24,   89,   77,   87,   27,  274,   35,   38,
 /*   290 */    37,  227,  228,   38,   37,   21,   88,   98,   36,    1,
 /*   300 */   226,   98,   49,   34,  231,   35,    2,   49,   38,   37,
 /*   310 */   272,  174,  173,   90,   56,   80,   98,  172,    5,  171,
 /*   320 */    35,  191,  270,  279,  231,  280,  170,   48,  157,  272,
 /*   330 */   231,  197,   90,   55,  156,  272,  175,  155,   90,   51,
 /*   340 */   231,  270,  279,  231,  280,  231,   48,  270,  279,  231,
 /*   350 */   280,  231,   48,  231,  231,  231,  272,  231,  231,   90,
 /*   360 */    60,  231,  272,  231,  231,   90,   52,  231,  270,  279,
 /*   370 */   231,  280,  231,   48,  270,  279,  231,  280,  231,   48,
 /*   380 */   272,  231,  231,   90,   61,  231,  231,  272,  231,  231,
 /*   390 */    90,   62,  270,  279,  231,  280,  231,   48,  231,  270,
 /*   400 */   279,  231,  280,  231,   48,  272,  231,  231,   90,   65,
 /*   410 */   231,  272,  231,  231,   90,   66,  231,  270,  279,  231,
 /*   420 */   280,  231,   48,  270,  279,  231,  280,  272,   48,  231,
 /*   430 */    90,   67,  231,  272,  231,  231,   90,   68,  231,  270,
 /*   440 */   279,  231,  280,  231,   48,  270,  279,  231,  280,  231,
 /*   450 */    48,  272,  231,  231,   90,   63,  231,  272,  231,  231,
 /*   460 */    90,   64,  231,  270,  279,  231,  280,  231,   48,  270,
 /*   470 */   279,  231,  280,  231,   48,  272,  231,  231,   90,   69,
 /*   480 */   231,  272,  231,  231,   90,  290,  231,  270,  279,  231,
 /*   490 */   280,  231,   48,  270,  279,  231,  280,  272,   48,  231,
 /*   500 */    90,  289,  231,  272,  231,  231,   90,  288,  231,  270,
 /*   510 */   279,  231,  280,  231,   48,  270,  279,  231,  280,  231,
 /*   520 */    48,  272,  231,  231,   90,   71,  231,  272,  231,  231,
 /*   530 */    90,  285,  231,  270,  279,  231,  280,  231,   48,  270,
 /*   540 */   279,  231,  280,  231,   48,  272,  231,  231,   90,   59,
 /*   550 */   231,  272,  231,  231,   90,   70,  231,  270,  279,  231,
 /*   560 */   280,  231,   48,  270,  279,  231,  280,  272,   48,  231,
 /*   570 */    90,   53,  231,  272,  231,  231,   90,   57,  231,  270,
 /*   580 */   279,  231,  280,  231,   48,  270,  279,  231,  280,  231,
 /*   590 */    48,   95,  272,  248,   74,   90,   54,  231,  231,  249,
 /*   600 */    92,   91,  231,  270,  270,  279,  231,  280,   16,   48,
 /*   610 */   231,   23,   20,   18,   19,   17,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    66,   78,    1,   69,   70,    1,   66,    1,   66,   69,
 /*    10 */    70,   77,   78,   79,   80,   81,    1,   83,   78,   79,
 /*    20 */    78,   81,   82,   83,   66,   67,   68,   69,   63,   64,
 /*    30 */    65,   31,   32,   33,   72,   73,   78,   37,   38,   39,
 /*    40 */    40,   41,   42,   43,    3,    4,   46,   47,   48,   49,
 /*    50 */    50,   46,   47,   48,   49,   50,   27,   57,   29,   30,
 /*    60 */    59,   57,   30,   31,   32,   33,   48,   49,   50,   37,
 /*    70 */    38,   39,   40,   41,   42,   43,   29,   30,   46,   47,
 /*    80 */    48,   49,   50,   27,   67,   29,   30,   46,   47,   31,
 /*    90 */    32,   33,   81,   68,   83,   37,   38,   39,   40,   41,
 /*   100 */    42,   43,    0,    1,   46,   47,   48,   49,   50,   78,
 /*   110 */    31,   32,   33,   27,   28,   57,   37,   38,   39,   40,
 /*   120 */    41,   42,   43,   66,   28,   46,   47,   48,   49,   50,
 /*   130 */    67,   31,   32,   33,    1,   78,   57,   37,   38,   39,
 /*   140 */    40,   41,   42,   43,   73,    1,   46,   47,   48,   49,
 /*   150 */    50,   33,   28,   57,   65,   37,   38,   39,   40,   41,
 /*   160 */    42,   43,   58,   68,   46,   47,   48,   49,   50,    1,
 /*   170 */     2,    3,    4,    1,   37,   38,   39,   40,   41,   42,
 /*   180 */    43,   57,   66,   46,   47,   48,   49,   50,    1,    2,
 /*   190 */     3,    4,   59,    1,   78,   39,   40,   41,   42,   43,
 /*   200 */    66,   57,   46,   47,   48,   49,   50,   26,    2,    3,
 /*   210 */     4,   69,   78,   68,   46,   47,    1,    2,    3,    4,
 /*   220 */    52,   53,   54,   55,   56,   57,   80,    1,    2,    3,
 /*   230 */     4,   28,   28,   46,   47,   77,   25,   56,   80,   52,
 /*   240 */    53,   54,   55,   56,    1,    2,    3,    4,    1,    2,
 /*   250 */     3,    4,   46,   47,   25,   27,   26,   29,   30,   57,
 /*   260 */    54,   46,   47,    1,    2,    3,    4,   52,   53,   54,
 /*   270 */    55,   56,   46,   47,   57,   27,   29,   30,   52,   53,
 /*   280 */    54,   55,   56,   26,   77,    1,   56,   80,   58,   46,
 /*   290 */    47,   29,   30,   46,   47,   52,   53,   54,   55,   56,
 /*   300 */     1,   54,   28,   56,   84,   58,   56,   28,   46,   47,
 /*   310 */    66,   25,   25,   69,   70,   71,   54,   25,   56,   25,
 /*   320 */    58,    1,   78,   79,   84,   81,   25,   83,   25,   66,
 /*   330 */    84,   57,   69,   70,   25,   66,   57,   25,   69,   70,
 /*   340 */    84,   78,   79,   84,   81,   84,   83,   78,   79,   84,
 /*   350 */    81,   84,   83,   84,   84,   84,   66,   84,   84,   69,
 /*   360 */    70,   84,   66,   84,   84,   69,   70,   84,   78,   79,
 /*   370 */    84,   81,   84,   83,   78,   79,   84,   81,   84,   83,
 /*   380 */    66,   84,   84,   69,   70,   84,   84,   66,   84,   84,
 /*   390 */    69,   70,   78,   79,   84,   81,   84,   83,   84,   78,
 /*   400 */    79,   84,   81,   84,   83,   66,   84,   84,   69,   70,
 /*   410 */    84,   66,   84,   84,   69,   70,   84,   78,   79,   84,
 /*   420 */    81,   84,   83,   78,   79,   84,   81,   66,   83,   84,
 /*   430 */    69,   70,   84,   66,   84,   84,   69,   70,   84,   78,
 /*   440 */    79,   84,   81,   84,   83,   78,   79,   84,   81,   84,
 /*   450 */    83,   66,   84,   84,   69,   70,   84,   66,   84,   84,
 /*   460 */    69,   70,   84,   78,   79,   84,   81,   84,   83,   78,
 /*   470 */    79,   84,   81,   84,   83,   66,   84,   84,   69,   70,
 /*   480 */    84,   66,   84,   84,   69,   70,   84,   78,   79,   84,
 /*   490 */    81,   84,   83,   78,   79,   84,   81,   66,   83,   84,
 /*   500 */    69,   70,   84,   66,   84,   84,   69,   70,   84,   78,
 /*   510 */    79,   84,   81,   84,   83,   78,   79,   84,   81,   84,
 /*   520 */    83,   66,   84,   84,   69,   70,   84,   66,   84,   84,
 /*   530 */    69,   70,   84,   78,   79,   84,   81,   84,   83,   78,
 /*   540 */    79,   84,   81,   84,   83,   66,   84,   84,   69,   70,
 /*   550 */    84,   66,   84,   84,   69,   70,   84,   78,   79,   84,
 /*   560 */    81,   84,   83,   78,   79,   84,   81,   66,   83,   84,
 /*   570 */    69,   70,   84,   66,   84,   84,   69,   70,   84,   78,
 /*   580 */    79,   84,   81,   84,   83,   78,   79,   84,   81,   84,
 /*   590 */    83,   66,   66,   68,   69,   69,   70,   84,   84,   74,
 /*   600 */    75,   76,   84,   78,   78,   79,   84,   81,   43,   83,
 /*   610 */    84,   46,   47,   48,   49,   50,   84,   84,   84,   84,
 /*   620 */    84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
 /*   630 */    84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
 /*   640 */    84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
 /*   650 */    84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
 /*   660 */    84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
 /*   670 */    84,   84,   63,   63,   63,   63,   63,   63,   63,
};
#define YY_SHIFT_COUNT    (101)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (565)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */     6,  187,  168,  215,  226,  226,  226,  226,  226,  226,
 /*    10 */   226,  226,  226,  226,  226,  226,  226,  226,  226,  226,
 /*    20 */   226,  226,  226,  226,  226,  243,  247,  226,  262,  206,
 /*    30 */   206,  206,  206,    4,  144,    1,   15,   41,   41,   29,
 /*    40 */    56,  228,  230,   47,  133,   47,  102,  104,  172,  192,
 /*    50 */   104,    0,   32,   58,   79,  100,  100,  100,  100,  100,
 /*    60 */   100,  118,  137,  156,  156,  565,  565,  565,  565,    5,
 /*    70 */    18,   18,   86,   96,  181,  124,  274,  279,  211,  203,
 /*    80 */   204,  229,  202,  217,  248,  248,  257,  250,  284,  299,
 /*    90 */   257,  286,  287,  292,  294,  301,  229,  303,  320,  309,
 /*   100 */   312,  211,
};
#define YY_REDUCE_COUNT (50)
#define YY_REDUCE_MIN   (-77)
#define YY_REDUCE_MAX   (526)
static const short yy_reduce_ofst[] = {
 /*     0 */   -35,  -66,  -60,  244,  263,  269,  290,  296,  314,  321,
 /*    10 */   339,  345,  361,  367,  385,  391,  409,  415,  431,  437,
 /*    20 */   455,  461,  479,  485,  501,  507,  525,  526,  -42,  -58,
 /*    30 */    57,  116,  134,  158,  207,  -38,   11,  -77,   31,   17,
 /*    40 */    17,   17,   25,   17,   71,   63,   89,   95,  142,  146,
 /*    50 */   145,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
 /*    10 */   229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
 /*    20 */   229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
 /*    30 */   229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
 /*    40 */   229,  305,  229,  229,  229,  305,  229,  305,  229,  275,
 /*    50 */   229,  229,  229,  229,  229,  242,  241,  278,  301,  302,
 /*    60 */   300,  299,  298,  293,  292,  297,  296,  295,  294,  291,
 /*    70 */   286,  287,  305,  229,  229,  229,  229,  229,  233,  265,
 /*    80 */   229,  246,  229,  229,  305,  229,  303,  229,  229,  229,
 /*    90 */   273,  229,  229,  229,  229,  229,  247,  229,  229,  229,
 /*   100 */   229,  234,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
    0,  /*          $ => nothing */
    0,  /*         ID => nothing */
    0,  /*     STRING => nothing */
    0,  /*    INTEGER => nothing */
    0,  /*      FLOAT => nothing */
    2,  /*        URL => STRING */
    0,  /*       NODE => nothing */
    0,  /*  CONTAINER => nothing */
    0,  /*      ENTRY => nothing */
    0,  /*     IMPORT => nothing */
    0,  /*      INPUT => nothing */
    0,  /*     OUTPUT => nothing */
    0,  /*     RETURN => nothing */
    0,  /*      ERROR => nothing */
    0,  /*    INCLUDE => nothing */
    1,  /*      MOUNT => ID */
    1,  /* ENVIRONMENT => ID */
    1,  /*     HEADER => ID */
    1,  /*       INIT => ID */
    1,  /*     LIMITS => ID */
    1,  /*       REPO => ID */
    1,  /*        CPU => ID */
    1,  /*        GPU => ID */
    1,  /*     MEMORY => ID */
    1,  /*        MBU => ID */
    0,  /*  SEMICOLON => nothing */
    0,  /*        DOT => nothing */
    0,  /*         AT => nothing */
    0,  /*      COMMA => nothing */
    0,  /*     EQUALS => nothing */
    0,  /*      COLON => nothing */
    0,  /*   QUESTION => nothing */
    0,  /*         OR => nothing */
    0,  /*        AND => nothing */
    0,  /*        BAR => nothing */
    0,  /*      CARET => nothing */
    0,  /*        AMP => nothing */
    0,  /*         NE => nothing */
    0,  /*         EQ => nothing */
    0,  /*         GT => nothing */
    0,  /*         LT => nothing */
    0,  /*         GE => nothing */
    0,  /*         LE => nothing */
    0,  /*       COMP => nothing */
    0,  /*        SHR => nothing */
    0,  /*        SHL => nothing */
    0,  /*       PLUS => nothing */
    0,  /*      MINUS => nothing */
    0,  /*       STAR => nothing */
    0,  /*      SLASH => nothing */
    0,  /*    PERCENT => nothing */
    0,  /*        POW => nothing */
    0,  /*       BANG => nothing */
    0,  /*      TILDA => nothing */
    0,  /*     DOLLAR => nothing */
    0,  /*       HASH => nothing */
    0,  /*    OPENPAR => nothing */
    0,  /*   CLOSEPAR => nothing */
    0,  /*    OPENBRA => nothing */
    0,  /*   CLOSEBRA => nothing */
    0,  /*    OPENSQB => nothing */
    0,  /*   CLOSESQB => nothing */
    0,  /*        ANY => nothing */
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  flow_parserARG_SDECL                /* A place to hold %extra_argument */
  flow_parserCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void flow_parserTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "ID",
  /*    2 */ "STRING",
  /*    3 */ "INTEGER",
  /*    4 */ "FLOAT",
  /*    5 */ "URL",
  /*    6 */ "NODE",
  /*    7 */ "CONTAINER",
  /*    8 */ "ENTRY",
  /*    9 */ "IMPORT",
  /*   10 */ "INPUT",
  /*   11 */ "OUTPUT",
  /*   12 */ "RETURN",
  /*   13 */ "ERROR",
  /*   14 */ "INCLUDE",
  /*   15 */ "MOUNT",
  /*   16 */ "ENVIRONMENT",
  /*   17 */ "HEADER",
  /*   18 */ "INIT",
  /*   19 */ "LIMITS",
  /*   20 */ "REPO",
  /*   21 */ "CPU",
  /*   22 */ "GPU",
  /*   23 */ "MEMORY",
  /*   24 */ "MBU",
  /*   25 */ "SEMICOLON",
  /*   26 */ "DOT",
  /*   27 */ "AT",
  /*   28 */ "COMMA",
  /*   29 */ "EQUALS",
  /*   30 */ "COLON",
  /*   31 */ "QUESTION",
  /*   32 */ "OR",
  /*   33 */ "AND",
  /*   34 */ "BAR",
  /*   35 */ "CARET",
  /*   36 */ "AMP",
  /*   37 */ "NE",
  /*   38 */ "EQ",
  /*   39 */ "GT",
  /*   40 */ "LT",
  /*   41 */ "GE",
  /*   42 */ "LE",
  /*   43 */ "COMP",
  /*   44 */ "SHR",
  /*   45 */ "SHL",
  /*   46 */ "PLUS",
  /*   47 */ "MINUS",
  /*   48 */ "STAR",
  /*   49 */ "SLASH",
  /*   50 */ "PERCENT",
  /*   51 */ "POW",
  /*   52 */ "BANG",
  /*   53 */ "TILDA",
  /*   54 */ "DOLLAR",
  /*   55 */ "HASH",
  /*   56 */ "OPENPAR",
  /*   57 */ "CLOSEPAR",
  /*   58 */ "OPENBRA",
  /*   59 */ "CLOSEBRA",
  /*   60 */ "OPENSQB",
  /*   61 */ "CLOSESQB",
  /*   62 */ "ANY",
  /*   63 */ "main",
  /*   64 */ "flow",
  /*   65 */ "stmt",
  /*   66 */ "valx",
  /*   67 */ "eqsc",
  /*   68 */ "blck",
  /*   69 */ "dtid",
  /*   70 */ "fldr",
  /*   71 */ "valc",
  /*   72 */ "list",
  /*   73 */ "elem",
  /*   74 */ "lblk",
  /*   75 */ "oexp",
  /*   76 */ "rexp",
  /*   77 */ "fldm",
  /*   78 */ "valn",
  /*   79 */ "vall",
  /*   80 */ "fldd",
  /*   81 */ "fldx",
  /*   82 */ "fldra",
  /*   83 */ "fldn",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "main ::= flow",
 /*   1 */ "flow ::= stmt",
 /*   2 */ "flow ::= flow stmt",
 /*   3 */ "stmt ::= ID valx SEMICOLON",
 /*   4 */ "stmt ::= ID eqsc valx SEMICOLON",
 /*   5 */ "stmt ::= ID ID eqsc valx SEMICOLON",
 /*   6 */ "stmt ::= ID blck",
 /*   7 */ "stmt ::= ID dtid blck",
 /*   8 */ "stmt ::= ID dtid OPENPAR fldr CLOSEPAR blck",
 /*   9 */ "stmt ::= ID OPENPAR fldr CLOSEPAR fldr",
 /*  10 */ "stmt ::= ID OPENPAR fldr CLOSEPAR valc COMMA fldr",
 /*  11 */ "stmt ::= stmt SEMICOLON",
 /*  12 */ "blck ::= OPENBRA list CLOSEBRA",
 /*  13 */ "blck ::= OPENBRA CLOSEBRA",
 /*  14 */ "list ::= elem",
 /*  15 */ "list ::= list elem",
 /*  16 */ "elem ::= ID blck",
 /*  17 */ "elem ::= ID lblk",
 /*  18 */ "elem ::= ID valx SEMICOLON",
 /*  19 */ "elem ::= ID EQUALS valx SEMICOLON",
 /*  20 */ "elem ::= ID COLON valx SEMICOLON",
 /*  21 */ "elem ::= ID oexp SEMICOLON",
 /*  22 */ "elem ::= ID rexp SEMICOLON",
 /*  23 */ "rexp ::= OPENPAR fldm CLOSEPAR",
 /*  24 */ "rexp ::= OPENPAR ID AT CLOSEPAR",
 /*  25 */ "rexp ::= OPENPAR CLOSEPAR",
 /*  26 */ "oexp ::= dtid OPENPAR ID AT CLOSEPAR",
 /*  27 */ "oexp ::= dtid OPENPAR fldm CLOSEPAR",
 /*  28 */ "oexp ::= dtid OPENPAR CLOSEPAR",
 /*  29 */ "elem ::= elem SEMICOLON",
 /*  30 */ "lblk ::= ID blck",
 /*  31 */ "valc ::= INTEGER",
 /*  32 */ "valc ::= ID",
 /*  33 */ "valn ::= INTEGER",
 /*  34 */ "valn ::= FLOAT",
 /*  35 */ "valn ::= PLUS valn",
 /*  36 */ "valn ::= MINUS valn",
 /*  37 */ "valx ::= STRING",
 /*  38 */ "valx ::= valn",
 /*  39 */ "valx ::= DOLLAR ID",
 /*  40 */ "vall ::= valx",
 /*  41 */ "vall ::= dtid",
 /*  42 */ "fldm ::= fldd",
 /*  43 */ "fldm ::= fldm COMMA",
 /*  44 */ "fldm ::= fldm COMMA fldd",
 /*  45 */ "fldd ::= ID eqsc OPENPAR fldm CLOSEPAR",
 /*  46 */ "fldd ::= ID eqsc fldr",
 /*  47 */ "fldr ::= vall",
 /*  48 */ "fldr ::= fldx",
 /*  49 */ "fldr ::= OPENPAR fldr CLOSEPAR",
 /*  50 */ "fldr ::= TILDA ID OPENPAR CLOSEPAR",
 /*  51 */ "fldr ::= TILDA ID OPENPAR fldra CLOSEPAR",
 /*  52 */ "fldr ::= HASH fldx",
 /*  53 */ "fldr ::= BANG fldr",
 /*  54 */ "fldr ::= fldr PLUS fldr",
 /*  55 */ "fldr ::= fldr MINUS fldr",
 /*  56 */ "fldr ::= fldr SLASH fldr",
 /*  57 */ "fldr ::= fldr STAR fldr",
 /*  58 */ "fldr ::= fldr PERCENT fldr",
 /*  59 */ "fldr ::= fldr COMP fldr",
 /*  60 */ "fldr ::= fldr EQ fldr",
 /*  61 */ "fldr ::= fldr NE fldr",
 /*  62 */ "fldr ::= fldr LT fldr",
 /*  63 */ "fldr ::= fldr GT fldr",
 /*  64 */ "fldr ::= fldr LE fldr",
 /*  65 */ "fldr ::= fldr GE fldr",
 /*  66 */ "fldr ::= fldr AND fldr",
 /*  67 */ "fldr ::= fldr OR fldr",
 /*  68 */ "fldr ::= fldr QUESTION fldr COLON fldr",
 /*  69 */ "fldra ::= fldr",
 /*  70 */ "fldra ::= fldra COMMA fldr",
 /*  71 */ "fldx ::= fldn dtid",
 /*  72 */ "fldn ::= ID AT",
 /*  73 */ "dtid ::= ID",
 /*  74 */ "dtid ::= dtid DOT ID",
 /*  75 */ "eqsc ::= EQUALS",
 /*  76 */ "eqsc ::= COLON",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to flow_parserAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void flow_parserInit(void *yypRawParser flow_parserCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  flow_parserCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef flow_parser_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to flow_parser and flow_parserFree.
*/
void *flow_parserAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) flow_parserCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    flow_parserCTX_STORE
    flow_parserInit(yypParser flow_parserCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* flow_parser_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  flow_parserARG_FETCH
  flow_parserCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void flow_parserFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef flow_parser_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void flow_parserFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  flow_parserFinalize(p);
  (*freeProc)(p);
}
#endif /* flow_parser_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int flow_parserStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int flow_parserCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   flow_parserARG_FETCH
   flow_parserCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   flow_parserARG_STORE /* Suppress warning about unused %extra_argument var */
   flow_parserCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  flow_parserTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    63,  /* (0) main ::= flow */
    64,  /* (1) flow ::= stmt */
    64,  /* (2) flow ::= flow stmt */
    65,  /* (3) stmt ::= ID valx SEMICOLON */
    65,  /* (4) stmt ::= ID eqsc valx SEMICOLON */
    65,  /* (5) stmt ::= ID ID eqsc valx SEMICOLON */
    65,  /* (6) stmt ::= ID blck */
    65,  /* (7) stmt ::= ID dtid blck */
    65,  /* (8) stmt ::= ID dtid OPENPAR fldr CLOSEPAR blck */
    65,  /* (9) stmt ::= ID OPENPAR fldr CLOSEPAR fldr */
    65,  /* (10) stmt ::= ID OPENPAR fldr CLOSEPAR valc COMMA fldr */
    65,  /* (11) stmt ::= stmt SEMICOLON */
    68,  /* (12) blck ::= OPENBRA list CLOSEBRA */
    68,  /* (13) blck ::= OPENBRA CLOSEBRA */
    72,  /* (14) list ::= elem */
    72,  /* (15) list ::= list elem */
    73,  /* (16) elem ::= ID blck */
    73,  /* (17) elem ::= ID lblk */
    73,  /* (18) elem ::= ID valx SEMICOLON */
    73,  /* (19) elem ::= ID EQUALS valx SEMICOLON */
    73,  /* (20) elem ::= ID COLON valx SEMICOLON */
    73,  /* (21) elem ::= ID oexp SEMICOLON */
    73,  /* (22) elem ::= ID rexp SEMICOLON */
    76,  /* (23) rexp ::= OPENPAR fldm CLOSEPAR */
    76,  /* (24) rexp ::= OPENPAR ID AT CLOSEPAR */
    76,  /* (25) rexp ::= OPENPAR CLOSEPAR */
    75,  /* (26) oexp ::= dtid OPENPAR ID AT CLOSEPAR */
    75,  /* (27) oexp ::= dtid OPENPAR fldm CLOSEPAR */
    75,  /* (28) oexp ::= dtid OPENPAR CLOSEPAR */
    73,  /* (29) elem ::= elem SEMICOLON */
    74,  /* (30) lblk ::= ID blck */
    71,  /* (31) valc ::= INTEGER */
    71,  /* (32) valc ::= ID */
    78,  /* (33) valn ::= INTEGER */
    78,  /* (34) valn ::= FLOAT */
    78,  /* (35) valn ::= PLUS valn */
    78,  /* (36) valn ::= MINUS valn */
    66,  /* (37) valx ::= STRING */
    66,  /* (38) valx ::= valn */
    66,  /* (39) valx ::= DOLLAR ID */
    79,  /* (40) vall ::= valx */
    79,  /* (41) vall ::= dtid */
    77,  /* (42) fldm ::= fldd */
    77,  /* (43) fldm ::= fldm COMMA */
    77,  /* (44) fldm ::= fldm COMMA fldd */
    80,  /* (45) fldd ::= ID eqsc OPENPAR fldm CLOSEPAR */
    80,  /* (46) fldd ::= ID eqsc fldr */
    70,  /* (47) fldr ::= vall */
    70,  /* (48) fldr ::= fldx */
    70,  /* (49) fldr ::= OPENPAR fldr CLOSEPAR */
    70,  /* (50) fldr ::= TILDA ID OPENPAR CLOSEPAR */
    70,  /* (51) fldr ::= TILDA ID OPENPAR fldra CLOSEPAR */
    70,  /* (52) fldr ::= HASH fldx */
    70,  /* (53) fldr ::= BANG fldr */
    70,  /* (54) fldr ::= fldr PLUS fldr */
    70,  /* (55) fldr ::= fldr MINUS fldr */
    70,  /* (56) fldr ::= fldr SLASH fldr */
    70,  /* (57) fldr ::= fldr STAR fldr */
    70,  /* (58) fldr ::= fldr PERCENT fldr */
    70,  /* (59) fldr ::= fldr COMP fldr */
    70,  /* (60) fldr ::= fldr EQ fldr */
    70,  /* (61) fldr ::= fldr NE fldr */
    70,  /* (62) fldr ::= fldr LT fldr */
    70,  /* (63) fldr ::= fldr GT fldr */
    70,  /* (64) fldr ::= fldr LE fldr */
    70,  /* (65) fldr ::= fldr GE fldr */
    70,  /* (66) fldr ::= fldr AND fldr */
    70,  /* (67) fldr ::= fldr OR fldr */
    70,  /* (68) fldr ::= fldr QUESTION fldr COLON fldr */
    82,  /* (69) fldra ::= fldr */
    82,  /* (70) fldra ::= fldra COMMA fldr */
    81,  /* (71) fldx ::= fldn dtid */
    83,  /* (72) fldn ::= ID AT */
    69,  /* (73) dtid ::= ID */
    69,  /* (74) dtid ::= dtid DOT ID */
    67,  /* (75) eqsc ::= EQUALS */
    67,  /* (76) eqsc ::= COLON */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) main ::= flow */
   -1,  /* (1) flow ::= stmt */
   -2,  /* (2) flow ::= flow stmt */
   -3,  /* (3) stmt ::= ID valx SEMICOLON */
   -4,  /* (4) stmt ::= ID eqsc valx SEMICOLON */
   -5,  /* (5) stmt ::= ID ID eqsc valx SEMICOLON */
   -2,  /* (6) stmt ::= ID blck */
   -3,  /* (7) stmt ::= ID dtid blck */
   -6,  /* (8) stmt ::= ID dtid OPENPAR fldr CLOSEPAR blck */
   -5,  /* (9) stmt ::= ID OPENPAR fldr CLOSEPAR fldr */
   -7,  /* (10) stmt ::= ID OPENPAR fldr CLOSEPAR valc COMMA fldr */
   -2,  /* (11) stmt ::= stmt SEMICOLON */
   -3,  /* (12) blck ::= OPENBRA list CLOSEBRA */
   -2,  /* (13) blck ::= OPENBRA CLOSEBRA */
   -1,  /* (14) list ::= elem */
   -2,  /* (15) list ::= list elem */
   -2,  /* (16) elem ::= ID blck */
   -2,  /* (17) elem ::= ID lblk */
   -3,  /* (18) elem ::= ID valx SEMICOLON */
   -4,  /* (19) elem ::= ID EQUALS valx SEMICOLON */
   -4,  /* (20) elem ::= ID COLON valx SEMICOLON */
   -3,  /* (21) elem ::= ID oexp SEMICOLON */
   -3,  /* (22) elem ::= ID rexp SEMICOLON */
   -3,  /* (23) rexp ::= OPENPAR fldm CLOSEPAR */
   -4,  /* (24) rexp ::= OPENPAR ID AT CLOSEPAR */
   -2,  /* (25) rexp ::= OPENPAR CLOSEPAR */
   -5,  /* (26) oexp ::= dtid OPENPAR ID AT CLOSEPAR */
   -4,  /* (27) oexp ::= dtid OPENPAR fldm CLOSEPAR */
   -3,  /* (28) oexp ::= dtid OPENPAR CLOSEPAR */
   -2,  /* (29) elem ::= elem SEMICOLON */
   -2,  /* (30) lblk ::= ID blck */
   -1,  /* (31) valc ::= INTEGER */
   -1,  /* (32) valc ::= ID */
   -1,  /* (33) valn ::= INTEGER */
   -1,  /* (34) valn ::= FLOAT */
   -2,  /* (35) valn ::= PLUS valn */
   -2,  /* (36) valn ::= MINUS valn */
   -1,  /* (37) valx ::= STRING */
   -1,  /* (38) valx ::= valn */
   -2,  /* (39) valx ::= DOLLAR ID */
   -1,  /* (40) vall ::= valx */
   -1,  /* (41) vall ::= dtid */
   -1,  /* (42) fldm ::= fldd */
   -2,  /* (43) fldm ::= fldm COMMA */
   -3,  /* (44) fldm ::= fldm COMMA fldd */
   -5,  /* (45) fldd ::= ID eqsc OPENPAR fldm CLOSEPAR */
   -3,  /* (46) fldd ::= ID eqsc fldr */
   -1,  /* (47) fldr ::= vall */
   -1,  /* (48) fldr ::= fldx */
   -3,  /* (49) fldr ::= OPENPAR fldr CLOSEPAR */
   -4,  /* (50) fldr ::= TILDA ID OPENPAR CLOSEPAR */
   -5,  /* (51) fldr ::= TILDA ID OPENPAR fldra CLOSEPAR */
   -2,  /* (52) fldr ::= HASH fldx */
   -2,  /* (53) fldr ::= BANG fldr */
   -3,  /* (54) fldr ::= fldr PLUS fldr */
   -3,  /* (55) fldr ::= fldr MINUS fldr */
   -3,  /* (56) fldr ::= fldr SLASH fldr */
   -3,  /* (57) fldr ::= fldr STAR fldr */
   -3,  /* (58) fldr ::= fldr PERCENT fldr */
   -3,  /* (59) fldr ::= fldr COMP fldr */
   -3,  /* (60) fldr ::= fldr EQ fldr */
   -3,  /* (61) fldr ::= fldr NE fldr */
   -3,  /* (62) fldr ::= fldr LT fldr */
   -3,  /* (63) fldr ::= fldr GT fldr */
   -3,  /* (64) fldr ::= fldr LE fldr */
   -3,  /* (65) fldr ::= fldr GE fldr */
   -3,  /* (66) fldr ::= fldr AND fldr */
   -3,  /* (67) fldr ::= fldr OR fldr */
   -5,  /* (68) fldr ::= fldr QUESTION fldr COLON fldr */
   -1,  /* (69) fldra ::= fldr */
   -3,  /* (70) fldra ::= fldra COMMA fldr */
   -2,  /* (71) fldx ::= fldn dtid */
   -2,  /* (72) fldn ::= ID AT */
   -1,  /* (73) dtid ::= ID */
   -3,  /* (74) dtid ::= dtid DOT ID */
   -1,  /* (75) eqsc ::= EQUALS */
   -1,  /* (76) eqsc ::= COLON */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  flow_parserTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  flow_parserCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  flow_parserARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* main ::= flow */
      case 1: /* flow ::= stmt */ yytestcase(yyruleno==1);
#line 54 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_ACCEPT, yymsp[0].minor.yy0); }
#line 1385 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 2: /* flow ::= flow stmt */
      case 15: /* list ::= list elem */ yytestcase(yyruleno==15);
#line 57 "flow-parser.y"
{ yylhsminor.yy0 = ast->nappend(yymsp[-1].minor.yy0, yymsp[0].minor.yy0); }
#line 1392 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 3: /* stmt ::= ID valx SEMICOLON */
#line 59 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(yymsp[-2].minor.yy0, yymsp[-1].minor.yy0); 
                                                               }
#line 1399 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 4: /* stmt ::= ID eqsc valx SEMICOLON */
#line 61 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(yymsp[-3].minor.yy0, yymsp[-1].minor.yy0); 
                                                               }
#line 1406 "flow-parser.c"
  yymsp[-3].minor.yy0 = yylhsminor.yy0;
        break;
      case 5: /* stmt ::= ID ID eqsc valx SEMICOLON */
#line 63 "flow-parser.y"
{ 
                                                                 yylhsminor.yy0 = ast->node(yymsp[-4].minor.yy0, yymsp[-3].minor.yy0, yymsp[-1].minor.yy0); 
                                                               }
#line 1414 "flow-parser.c"
  yymsp[-4].minor.yy0 = yylhsminor.yy0;
        break;
      case 6: /* stmt ::= ID blck */
#line 67 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(yymsp[-1].minor.yy0, yymsp[0].minor.yy0);
                                                               }
#line 1421 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 7: /* stmt ::= ID dtid blck */
#line 70 "flow-parser.y"
{ yylhsminor.yy0 = ast->node( yymsp[-2].minor.yy0, yymsp[-1].minor.yy0, yymsp[0].minor.yy0); 
                                                               }
#line 1428 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 8: /* stmt ::= ID dtid OPENPAR fldr CLOSEPAR blck */
#line 73 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(yymsp[-5].minor.yy0, yymsp[-4].minor.yy0, yymsp[0].minor.yy0, yymsp[-2].minor.yy0); 
                                                               }
#line 1435 "flow-parser.c"
  yymsp[-5].minor.yy0 = yylhsminor.yy0;
        break;
      case 9: /* stmt ::= ID OPENPAR fldr CLOSEPAR fldr */
#line 76 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(yymsp[-4].minor.yy0, yymsp[-2].minor.yy0, yymsp[0].minor.yy0);
                                                               }
#line 1442 "flow-parser.c"
  yymsp[-4].minor.yy0 = yylhsminor.yy0;
        break;
      case 10: /* stmt ::= ID OPENPAR fldr CLOSEPAR valc COMMA fldr */
#line 78 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(yymsp[-6].minor.yy0, yymsp[-4].minor.yy0, yymsp[-2].minor.yy0, yymsp[0].minor.yy0);
                                                               }
#line 1449 "flow-parser.c"
  yymsp[-6].minor.yy0 = yylhsminor.yy0;
        break;
      case 11: /* stmt ::= stmt SEMICOLON */
      case 29: /* elem ::= elem SEMICOLON */ yytestcase(yyruleno==29);
      case 43: /* fldm ::= fldm COMMA */ yytestcase(yyruleno==43);
      case 72: /* fldn ::= ID AT */ yytestcase(yyruleno==72);
#line 80 "flow-parser.y"
{ yylhsminor.yy0 = yymsp[-1].minor.yy0; }
#line 1458 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 12: /* blck ::= OPENBRA list CLOSEBRA */
      case 49: /* fldr ::= OPENPAR fldr CLOSEPAR */ yytestcase(yyruleno==49);
#line 84 "flow-parser.y"
{ yymsp[-2].minor.yy0 = yymsp[-1].minor.yy0; }
#line 1465 "flow-parser.c"
        break;
      case 13: /* blck ::= OPENBRA CLOSEBRA */
#line 85 "flow-parser.y"
{ yylhsminor.yy0 = ast->chtype(yymsp[-1].minor.yy0, FTK_blck); }
#line 1470 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 14: /* list ::= elem */
#line 89 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_blck, yymsp[0].minor.yy0); }
#line 1476 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 16: /* elem ::= ID blck */
#line 95 "flow-parser.y"
{ /*
                                                                 ast->chtype(yymsp[0].minor.yy0, ast->blck_keyw(yymsp[-1].minor.yy0));
                                                                 if(ast->at(yymsp[0].minor.yy0).type == FTK_MOUNT) {
                                                                    yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-1].minor.yy0, ast->node(FTK_MOUNT, yymsp[0].minor.yy0));
                                                                    ast->chtype(yymsp[0].minor.yy0, FTK_blck);
                                                                 } else {
                                                                    yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-1].minor.yy0, yymsp[0].minor.yy0);
                                                                 }
                                                                 ast->expect(yymsp[0].minor.yy0, {FTK_HEADERS, FTK_ENVIRONMENT, FTK_MOUNT, FTK_blck}, "expected \"headers\", \"environment\", or \"mount\" here"); 
                                                                 */
                                                                 yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-1].minor.yy0, yymsp[0].minor.yy0);
                                                               }
#line 1493 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 17: /* elem ::= ID lblk */
#line 107 "flow-parser.y"
{ 
                                                                 yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-1].minor.yy0, yymsp[0].minor.yy0); 
                                                               }
#line 1501 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 18: /* elem ::= ID valx SEMICOLON */
#line 110 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-2].minor.yy0, yymsp[-1].minor.yy0); }
#line 1507 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 19: /* elem ::= ID EQUALS valx SEMICOLON */
      case 20: /* elem ::= ID COLON valx SEMICOLON */ yytestcase(yyruleno==20);
      case 27: /* oexp ::= dtid OPENPAR fldm CLOSEPAR */ yytestcase(yyruleno==27);
#line 111 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-3].minor.yy0, yymsp[-1].minor.yy0); }
#line 1515 "flow-parser.c"
  yymsp[-3].minor.yy0 = yylhsminor.yy0;
        break;
      case 21: /* elem ::= ID oexp SEMICOLON */
#line 113 "flow-parser.y"
{ 
                                                                 yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-2].minor.yy0, yymsp[-1].minor.yy0);
                                                               }
#line 1523 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 22: /* elem ::= ID rexp SEMICOLON */
#line 116 "flow-parser.y"
{ 
                                                                 yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-2].minor.yy0, yymsp[-1].minor.yy0); 
                                                               }
#line 1531 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 23: /* rexp ::= OPENPAR fldm CLOSEPAR */
#line 119 "flow-parser.y"
{ yymsp[-2].minor.yy0 = ast->node(FTK_elem, yymsp[-1].minor.yy0); }
#line 1537 "flow-parser.c"
        break;
      case 24: /* rexp ::= OPENPAR ID AT CLOSEPAR */
#line 120 "flow-parser.y"
{ yymsp[-3].minor.yy0 = ast->node(FTK_elem, ast->node(FTK_fldx, yymsp[-2].minor.yy0)); }
#line 1542 "flow-parser.c"
        break;
      case 25: /* rexp ::= OPENPAR CLOSEPAR */
#line 121 "flow-parser.y"
{ yymsp[-1].minor.yy0 = ast->node(FTK_elem, ast->node(FTK_fldm)); }
#line 1547 "flow-parser.c"
        break;
      case 26: /* oexp ::= dtid OPENPAR ID AT CLOSEPAR */
#line 122 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-4].minor.yy0, ast->node(FTK_fldx, yymsp[-2].minor.yy0)); }
#line 1552 "flow-parser.c"
  yymsp[-4].minor.yy0 = yylhsminor.yy0;
        break;
      case 28: /* oexp ::= dtid OPENPAR CLOSEPAR */
#line 124 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_elem, yymsp[-2].minor.yy0, ast->node(FTK_fldm)); }
#line 1558 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 30: /* lblk ::= ID blck */
#line 128 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_lblk, yymsp[-1].minor.yy0, yymsp[0].minor.yy0); }
#line 1564 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 31: /* valc ::= INTEGER */
      case 32: /* valc ::= ID */ yytestcase(yyruleno==32);
      case 33: /* valn ::= INTEGER */ yytestcase(yyruleno==33);
      case 34: /* valn ::= FLOAT */ yytestcase(yyruleno==34);
      case 37: /* valx ::= STRING */ yytestcase(yyruleno==37);
      case 38: /* valx ::= valn */ yytestcase(yyruleno==38);
      case 40: /* vall ::= valx */ yytestcase(yyruleno==40);
      case 41: /* vall ::= dtid */ yytestcase(yyruleno==41);
      case 42: /* fldm ::= fldd */ yytestcase(yyruleno==42);
      case 47: /* fldr ::= vall */ yytestcase(yyruleno==47);
      case 48: /* fldr ::= fldx */ yytestcase(yyruleno==48);
#line 131 "flow-parser.y"
{ yylhsminor.yy0 = yymsp[0].minor.yy0; }
#line 1580 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 35: /* valn ::= PLUS valn */
      case 36: /* valn ::= MINUS valn */ yytestcase(yyruleno==36);
#line 137 "flow-parser.y"
{ yymsp[-1].minor.yy0 = yymsp[0].minor.yy0; }
#line 1587 "flow-parser.c"
        break;
      case 39: /* valx ::= DOLLAR ID */
#line 144 "flow-parser.y"
{ yymsp[-1].minor.yy0 = ast->node(yymsp[0].minor.yy0); 
                                                               }
#line 1593 "flow-parser.c"
        break;
      case 44: /* fldm ::= fldm COMMA fldd */
      case 70: /* fldra ::= fldra COMMA fldr */ yytestcase(yyruleno==70);
#line 155 "flow-parser.y"
{ yylhsminor.yy0 = ast->nappend(yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1599 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 45: /* fldd ::= ID eqsc OPENPAR fldm CLOSEPAR */
#line 159 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldd, yymsp[-4].minor.yy0, yymsp[-1].minor.yy0); }
#line 1605 "flow-parser.c"
  yymsp[-4].minor.yy0 = yylhsminor.yy0;
        break;
      case 46: /* fldd ::= ID eqsc fldr */
#line 160 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldd, yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1611 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 50: /* fldr ::= TILDA ID OPENPAR CLOSEPAR */
#line 168 "flow-parser.y"
{ yymsp[-3].minor.yy0 = ast->node(FTK_fldr, yymsp[-2].minor.yy0); }
#line 1617 "flow-parser.c"
        break;
      case 51: /* fldr ::= TILDA ID OPENPAR fldra CLOSEPAR */
#line 169 "flow-parser.y"
{ yymsp[-4].minor.yy0 = ast->nprepend(yymsp[-1].minor.yy0, yymsp[-3].minor.yy0); }
#line 1622 "flow-parser.c"
        break;
      case 52: /* fldr ::= HASH fldx */
      case 53: /* fldr ::= BANG fldr */ yytestcase(yyruleno==53);
#line 170 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldr, yymsp[-1].minor.yy0, yymsp[0].minor.yy0); }
#line 1628 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 54: /* fldr ::= fldr PLUS fldr */
      case 55: /* fldr ::= fldr MINUS fldr */ yytestcase(yyruleno==55);
      case 56: /* fldr ::= fldr SLASH fldr */ yytestcase(yyruleno==56);
      case 57: /* fldr ::= fldr STAR fldr */ yytestcase(yyruleno==57);
      case 58: /* fldr ::= fldr PERCENT fldr */ yytestcase(yyruleno==58);
      case 59: /* fldr ::= fldr COMP fldr */ yytestcase(yyruleno==59);
      case 60: /* fldr ::= fldr EQ fldr */ yytestcase(yyruleno==60);
      case 61: /* fldr ::= fldr NE fldr */ yytestcase(yyruleno==61);
      case 62: /* fldr ::= fldr LT fldr */ yytestcase(yyruleno==62);
      case 63: /* fldr ::= fldr GT fldr */ yytestcase(yyruleno==63);
      case 64: /* fldr ::= fldr LE fldr */ yytestcase(yyruleno==64);
      case 65: /* fldr ::= fldr GE fldr */ yytestcase(yyruleno==65);
      case 66: /* fldr ::= fldr AND fldr */ yytestcase(yyruleno==66);
      case 67: /* fldr ::= fldr OR fldr */ yytestcase(yyruleno==67);
#line 172 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldr, yymsp[-1].minor.yy0, yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1647 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 68: /* fldr ::= fldr QUESTION fldr COLON fldr */
#line 186 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldr, yymsp[-3].minor.yy0, yymsp[-4].minor.yy0, yymsp[-2].minor.yy0, yymsp[0].minor.yy0); }
#line 1653 "flow-parser.c"
  yymsp[-4].minor.yy0 = yylhsminor.yy0;
        break;
      case 69: /* fldra ::= fldr */
#line 188 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_fldr, yymsp[0].minor.yy0); }
#line 1659 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 71: /* fldx ::= fldn dtid */
#line 193 "flow-parser.y"
{ yylhsminor.yy0 = ast->chtype(ast->nprepend(yymsp[0].minor.yy0, yymsp[-1].minor.yy0), FTK_fldx); }
#line 1665 "flow-parser.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 73: /* dtid ::= ID */
#line 202 "flow-parser.y"
{ yylhsminor.yy0 = ast->node(FTK_dtid, yymsp[0].minor.yy0);
                                                               }
#line 1672 "flow-parser.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 74: /* dtid ::= dtid DOT ID */
#line 204 "flow-parser.y"
{ yylhsminor.yy0 = ast->nappend(yymsp[-2].minor.yy0, yymsp[0].minor.yy0); 
                                                               }
#line 1679 "flow-parser.c"
  yymsp[-2].minor.yy0 = yylhsminor.yy0;
        break;
      case 75: /* eqsc ::= EQUALS */
#line 207 "flow-parser.y"
{  }
#line 1685 "flow-parser.c"
        break;
      case 76: /* eqsc ::= COLON */
#line 208 "flow-parser.y"
{ }
#line 1690 "flow-parser.c"
        break;
      default:
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  flow_parserARG_FETCH
  flow_parserCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 50 "flow-parser.y"

    ast->node(FTK_FAILED, ast->root());
#line 1737 "flow-parser.c"
/************ End %parse_failure code *****************************************/
  flow_parserARG_STORE /* Suppress warning about unused %extra_argument variable */
  flow_parserCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  flow_parserTOKENTYPE yyminor         /* The minor type of the error token */
){
  flow_parserARG_FETCH
  flow_parserCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 44 "flow-parser.y"

    ast->error(ast->input_filename, "syntax");
#line 1759 "flow-parser.c"
/************ End %syntax_error code ******************************************/
  flow_parserARG_STORE /* Suppress warning about unused %extra_argument variable */
  flow_parserCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  flow_parserARG_FETCH
  flow_parserCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
#line 47 "flow-parser.y"

    //std::cerr << "parsed just fine, ast size: " << ast->store.size() << " root: " << ast->store.back().children[0] << "\n";
#line 1788 "flow-parser.c"
/*********** End %parse_accept code *******************************************/
  flow_parserARG_STORE /* Suppress warning about unused %extra_argument variable */
  flow_parserCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "flow_parserAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void flow_parser(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  flow_parserTOKENTYPE yyminor       /* The value for the token */
  flow_parserARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  flow_parserCTX_FETCH
  flow_parserARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
#if YYSTACKDEPTH>0 
        if( yypParser->yytos>=yypParser->yystackEnd ){
          yyStackOverflow(yypParser);
          break;
        }
#else
        if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
#endif
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor flow_parserCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int flow_parserFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
