#define FTK_ID                               1
#define FTK_STRING                           2
#define FTK_INTEGER                          3
#define FTK_FLOAT                            4
#define FTK_URL                              5
#define FTK_KEYW                             6
#define FTK_CONTAINER                        7
#define FTK_ENTRY                            8
#define FTK_ERRCHK                           9
#define FTK_GROUP                           10
#define FTK_IMPORT                          11
#define FTK_INCLUDE                         12
#define FTK_INPUT                           13
#define FTK_NODE                            14
#define FTK_OUTPUT                          15
#define FTK_RETURN                          16
#define FTK_PROP                            17
#define FTK_CPU                             18
#define FTK_ENDPOINT                        19
#define FTK_ENVIRONMENT                     20
#define FTK_GPU                             21
#define FTK_HEADER                          22
#define FTK_IMAGE                           23
#define FTK_INIT                            24
#define FTK_LIMIT                           25
#define FTK_MBU                             26
#define FTK_MEMORY                          27
#define FTK_MOUNT                           28
#define FTK_PORT                            29
#define FTK_REPO                            30
#define FTK_SEMICOLON                       31
#define FTK_COMMA                           32
#define FTK_EQUALS                          33
#define FTK_COLON                           34
#define FTK_QUESTION                        35
#define FTK_OR                              36
#define FTK_AND                             37
#define FTK_BAR                             38
#define FTK_CARET                           39
#define FTK_AMP                             40
#define FTK_NE                              41
#define FTK_EQ                              42
#define FTK_GT                              43
#define FTK_LT                              44
#define FTK_GE                              45
#define FTK_LE                              46
#define FTK_COMP                            47
#define FTK_SHR                             48
#define FTK_SHL                             49
#define FTK_PLUS                            50
#define FTK_MINUS                           51
#define FTK_STAR                            52
#define FTK_SLASH                           53
#define FTK_PERCENT                         54
#define FTK_POW                             55
#define FTK_BANG                            56
#define FTK_TILDA                           57
#define FTK_DOLLAR                          58
#define FTK_HASH                            59
#define FTK_OPENPAR                         60
#define FTK_CLOSEPAR                        61
#define FTK_OPENBRA                         62
#define FTK_CLOSEBRA                        63
#define FTK_OPENSQB                         64
#define FTK_CLOSESQB                        65
#define FTK_DOT                             66
#define FTK_AT                              67
#define FTK_ANY                             68
