#define FTK_ID                               1
#define FTK_STRING                           2
#define FTK_INTEGER                          3
#define FTK_FLOAT                            4
#define FTK_SYMBOL                           5
#define FTK_NODE                             6
#define FTK_CONTAINER                        7
#define FTK_ENTRY                            8
#define FTK_IMPORT                           9
#define FTK_DEFINE                          10
#define FTK_OUTPUT                          11
#define FTK_RETURN                          12
#define FTK_ERROR                           13
#define FTK_ENDPOINT                        14
#define FTK_IMAGE                           15
#define FTK_MOUNT                           16
#define FTK_ENVIRONMENT                     17
#define FTK_INPUT                           18
#define FTK_SEMICOLON                       19
#define FTK_DOT                             20
#define FTK_AT                              21
#define FTK_COMMA                           22
#define FTK_EQUALS                          23
#define FTK_COLON                           24
#define FTK_SHLEQ2                          25
#define FTK_SHLEQ3                          26
#define FTK_SHLEQ4                          27
#define FTK_SHLEQ5                          28
#define FTK_SHLEQ6                          29
#define FTK_SHLEQ7                          30
#define FTK_SHLEQ8                          31
#define FTK_SHREQ2                          32
#define FTK_SHREQ3                          33
#define FTK_SHREQ4                          34
#define FTK_SHREQ5                          35
#define FTK_SHREQ6                          36
#define FTK_SHREQ7                          37
#define FTK_SHREQ8                          38
#define FTK_SHLEQ                           39
#define FTK_SHREQ                           40
#define FTK_QUESTION                        41
#define FTK_OR                              42
#define FTK_AND                             43
#define FTK_BAR                             44
#define FTK_CARET                           45
#define FTK_AMP                             46
#define FTK_NE                              47
#define FTK_EQ                              48
#define FTK_GT                              49
#define FTK_LT                              50
#define FTK_GE                              51
#define FTK_LE                              52
#define FTK_COMP                            53
#define FTK_SHR                             54
#define FTK_SHL                             55
#define FTK_PLUS                            56
#define FTK_MINUS                           57
#define FTK_STAR                            58
#define FTK_SLASH                           59
#define FTK_PERCENT                         60
#define FTK_BANG                            61
#define FTK_TILDA                           62
#define FTK_DOLLAR                          63
#define FTK_HASH                            64
#define FTK_UMINUS                          65
#define FTK_OPENPAR                         66
#define FTK_CLOSEPAR                        67
#define FTK_OPENBRA                         68
#define FTK_CLOSEBRA                        69
#define FTK_OPENSQB                         70
#define FTK_CLOSESQB                        71
