---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{NAME}}-{{G_NODE_GROUP}}
  labels:
    app: {{NAME}}-{{G_NODE_GROUP}}
    flow-group: {{NAME}}
spec:
  replicas: ${replicas_{{NAME/id/upper}}_{{G_NODE_GROUP/id/upper}}}
  selector:
    matchLabels:
      app: {{NAME}}-{{G_NODE_GROUP}}
  template:
    metadata:
      labels:
        app: {{NAME}}-{{G_NODE_GROUP}}
        flow-group: {{NAME}}
    spec:
{X:HAVE_IMAGE_PULL_SECRETS{
      imagePullSecrets:{{HAVE_IMAGE_PULL_SECRETS}}}X}
{S:IMAGE_PULL_SECRET{
      - name: "{{IMAGE_PULL_SECRET}}"
}S}
{X:HAVE_INIT_CONTAINERS{
      initContainers:{{HAVE_INIT_CONTAINERS}}}X}
{I:G_INIT_CONTAINER{
      - {{G_INIT_CONTAINER}}
}I}
{W:VOLUME_NAME{
${{{VOLUME_NAME/id/upper}}_ART}      - command: ["/bin/sh", "-c", "/usr/local/bin/artiget.sh '${{{VOLUME_NAME/id/upper}}}' --api-key-file /etc/artifactory/api-key -u -o /to-1"]
${{{VOLUME_NAME/id/upper}}_COS}      - command: ["/bin/sh", "-c", "/usr/local/bin/rr-get.sh '${{{VOLUME_NAME/id/upper}}}' -d /etc/cos-access -u -o /to-1"]
${{{VOLUME_NAME/id/upper}}_PVC}      - command: ["/bin/sh", "-c", "rsync -vrtlog /from-1/. /to-1"] 
        image:  "{{PUSH_REPO-}}{{IMAGE}}" 
        securityContext: {privileged: true, runAsUser: 0} 
        name: volumes-init-{{VOLUME_NAME/option}}
        volumeMounts:
${{{VOLUME_NAME/id/upper}}_PVC}        - name: {{VOLUME_NAME/option}}
${{{VOLUME_NAME/id/upper}}_PVC}          mountPath: "/from-1"
${{{VOLUME_NAME/id/upper}}_PVC}          readOnly: true
${{{VOLUME_NAME/id/upper}}_COS}        - name: cos-access-{{VOLUME_NAME/option}}
${{{VOLUME_NAME/id/upper}}_COS}          mountPath: "/etc/cos-access"
${{{VOLUME_NAME/id/upper}}_COS}          readOnly: true
${{{VOLUME_NAME/id/upper}}_ART}        - name: api-key-{{VOLUME_NAME/option}}
${{{VOLUME_NAME/id/upper}}_ART}          mountPath: "/etc/artifactory"
${{{VOLUME_NAME/id/upper}}_ART}          readOnly: true

        - name: scratch-{{VOLUME_NAME/option}}
          mountPath: "/to-1"
          readOnly: false
}W}
      containers:
{N:G_NODE_NAME{
{{G_EXTERN_NODE}}      - name: {{G_NODE_OPTION}}
{{G_EXTERN_NODE}}        image: "{{G_NODE_IMAGE}}"
{{G_EXTERN_NODE}}        {{G_NODE_ENVIRONMENT}}
{{G_EXTERN_NODE}}        {{G_NODE_MOUNTS}}
{{G_EXTERN_NODE}}{{G_NODE_HAVE_MIN_MAX}}        resources:
{{G_EXTERN_NODE}}{{G_NODE_HAVE_MIN}}          requests:
{{G_EXTERN_NODE}}{{G_NODE_HAVE_MIN_MEMORY}}            memory: "{{G_NODE_MIN_MEMORY}}"
{{G_EXTERN_NODE}}{{G_NODE_HAVE_MIN_CPUS}}            cpu: "{{G_NODE_MIN_CPUS}}"
{{G_EXTERN_NODE}}{{G_NODE_HAVE_MIN_GPUS}}            nvidia.com/gpu: "{{G_NODE_MIN_GPUS}}"
{{G_EXTERN_NODE}}{{G_NODE_HAVE_MAX}}          limis:
{{G_EXTERN_NODE}}{{G_NODE_HAVE_MAX_MEMORY}}            memory: "{{G_NODE_MAX_MEMORY}}"
{{G_EXTERN_NODE}}{{G_NODE_HAVE_MAX_CPUS}}            cpu: "{{G_NODE_MAX_CPUS}}"
{{G_EXTERN_NODE}}{{G_NODE_HAVE_MAX_GPUS}}            nvidia.com/gpu: "{{G_NODE_MAX_GPUS}}"
}N}
{V:HAVE_VOLUMES{
      volumes:{{HAVE_VOLUMES}}
}V}
{W:VOLUME_NAME{
${{{VOLUME_NAME/id/upper}}_PVC}        - name: {{VOLUME_NAME/option}}
${{{VOLUME_NAME/id/upper}}_PVC}          persistentVolumeClaim:
${{{VOLUME_NAME/id/upper}}_PVC}            claimName: ${{{VOLUME_NAME/id/upper}}}
${{{VOLUME_NAME/id/upper}}_COS}        - name: cos-access-{{VOLUME_NAME/option}}
${{{VOLUME_NAME/id/upper}}_COS}          secret:
${{{VOLUME_NAME/id/upper}}_COS}            secretName: ${{{VOLUME_NAME/id/upper}}_SECRET_NAME}
${{{VOLUME_NAME/id/upper}}_ART}        - name: api-key-{{VOLUME_NAME/option}}
${{{VOLUME_NAME/id/upper}}_ART}          secret:
${{{VOLUME_NAME/id/upper}}_ART}            secretName: ${{{VOLUME_NAME/id/upper}}_SECRET_NAME}
        - name: scratch-{{VOLUME_NAME/option}}
          emptyDir: {}
}W}
---
apiVersion: v1
kind: Service
metadata:
  name: {{NAME}}-{{G_NODE_GROUP}}
  labels:
    app: {{NAME}}-{{G_NODE_GROUP}}
    flow-group: {{NAME}}
spec:
  ports:
{N:G_NODE_NAME{
{{G_EXTERN_NODE}}  - port: {{G_IMAGE_PORT}}
{{G_EXTERN_NODE}}    protocol: TCP
{{G_EXTERN_NODE}}    name: {{G_NODE_OPTION}}-port
}N}
  selector:
    app: {{NAME}}-{{G_NODE_GROUP}}
