${use_COMPOSE}version: '2.3'
${use_SWARM}version: '3.7'
services:
  {{NAME}}:
    environment: 
      {{NAME/id/upper}}_REST_LISTENING_PORTS: "{{REST_PORT}}"
{N:NODE_NAME{{E?NODE_ENDPOINT{      {{NAME/id/upper}}_NODE_{{NODE_NAME/id/upper}}_ENDPOINT: "{{NODE_ENDPOINT}}"}E}
}N}
{N:NODE_NAME{{E?NODE_IMAGE{      {{NAME/id/upper}}_NODE_{{NODE_NAME/id/upper}}_ENDPOINT: "${{NAME/id/upper}}_NODE_{{NODE_NAME/id/upper}}_ENDPOINT_DN:{{NODE_PORT}}"}E}
}N}
    image: "{{PUSH_REPO-}}{{IMAGE}}"
    ports: ["$grpc_PORT:{{MAIN_PORT}}", "$rest_PORT:{{REST_PORT}}"]
$enable_custom_app    volumes: 
$enable_custom_app      - ${{NAME/id/upper}}_HTDOCS:/home/worker/{{NAME}}/app:ro
    command: ["/home/worker/{{NAME}}/{{NAME}}-server", "{{MAIN_PORT}}"]
$use_SWARM    deploy:
$use_SWARM        replicas: $replicas_{{NAME/id/upper}}
{N:NODE_NAME{{I?NODE_IMAGE{
  {{NODE_NAME}}:
    image: "$image_{{NODE_NAME/id/upper}}"
{{HAVE_RW_VOLUMES}}    group_add:
{{HAVE_RW_VOLUMES}}      - $docker_compose_RW_GID
$export_PORTS    ports: ["{{NODE_PORT}}:{{IMAGE_PORT}}"]
$default_RUNTIME{{SET_NODE_RUNTIME}}    runtime: {{NODE_RUNTIME}}
    {{NODE_ENVIRONMENT-}}
    {{NODE_MOUNTS-}}
$use_SWARM    deploy:
$use_SWARM        endpoint_mode: dnsrr
$use_SWARM        replicas: $scale_{{NODE_NAME/id/upper}}
{{NODE_HAVE_MIN_MAX}}$use_SWARM        resources:
{{NODE_HAVE_MIN}}$use_SWARM                reservations:
{{NODE_HAVE_MIN_MEMORY}}$use_SWARM                    memory: {{NODE_MIN_MEMORY}}
{{NODE_HAVE_MIN_CPUS}}$use_SWARM                    cpus: {{NODE_MIN_CPUS}}
{{NODE_HAVE_MAX}}$use_SWARM                limits:
{{NODE_HAVE_MAX_MEMORY}}$use_SWARM                    memory: {{NODE_MAX_MEMORY}}
{{NODE_HAVE_MAX_CPUS}}$use_SWARM                    cpus: {{NODE_MAX_CPUS}}
}I}
}N}
{V:HAVE_VOLUMES{
volumes:{{HAVE_VOLUMES}}
}V}
{W:VOLUME_NAME{
{{VOLUME_COMMENT/shcom-}}
    {{VOLUME_NAME}}:
        driver_opts:
            type: none
            o: bind
            device: ${{{VOLUME_NAME/upper}}}
}W}
