${use_COMPOSE}version: '2.3'
${use_SWARM}version: '3.7'
services:
  {{NAME}}:
    environment: 
      {{NAME/id/upper}}_REST_PORT: "{{REST_PORT}}"
{E:MAIN_EP_ENVIRONMENT_NAME{      {{MAIN_EP_ENVIRONMENT_NAME}}: "{{MAIN_EP_ENVIRONMENT_VALUE}}"
}E}
    image: "{{PUSH_REPO-}}{{IMAGE}}"
    ports: ["$grpc_PORT:{{MAIN_PORT}}", "$rest_PORT:{{REST_PORT}}"]
$enable_custom_app    volumes: 
$enable_custom_app      - ${{NAME/id/upper}}_HTDOCS:/home/worker/{{NAME}}/app:ro
    command: ["/home/worker/{{NAME}}/{{NAME}}-server", "{{MAIN_PORT}}"]
{N:NODE_NAME{
{{EXTERN_NODE}}  {{NODE_NAME}}:
{{EXTERN_NODE}}    image: "{{NODE_IMAGE}}"
{{EXTERN_NODE}}{{HAVE_RW_VOLUMES}}    group_add:
{{EXTERN_NODE}}{{HAVE_RW_VOLUMES}}      - $docker_compose_RW_GID
{{EXTERN_NODE}}$export_PORTS    ports: ["{{NODE_PORT}}:{{IMAGE_PORT}}"]
{{EXTERN_NODE}}$default_RUNTIME{{SET_NODE_RUNTIME}}    runtime: {{NODE_RUNTIME}}
{{EXTERN_NODE}}    {{NODE_ENVIRONMENT-}}
{{EXTERN_NODE}}    {{NODE_MOUNTS-}}
{{EXTERN_NODE}}$use_SWARM    deploy:
{{EXTERN_NODE}}$use_SWARM        endpoint_mode: dnsrr
{{EXTERN_NODE}}$use_SWARM            replicas: $scale_{{NODE_NAME/id/upper}}
{{EXTERN_NODE}}{{NODE_HAVE_MIN_MAX}}$use_SWARM            resources:
{{EXTERN_NODE}}{{NODE_HAVE_MIN}}$use_SWARM                reservations:
{{EXTERN_NODE}}{{NODE_HAVE_MIN_MEMORY}}$use_SWARM                    memory: {{NODE_MIN_MEMORY}}
{{EXTERN_NODE}}{{NODE_HAVE_MIN_CPUS}}$use_SWARM                    cpus: {{NODE_MIN_CPUS}}
{{EXTERN_NODE}}{{NODE_HAVE_MAX}}$use_SWARM                limits:
{{EXTERN_NODE}}{{NODE_HAVE_MAX_MEMORY}}$use_SWARM                    memory: {{NODE_MAX_MEMORY}}
{{EXTERN_NODE}}{{NODE_HAVE_MAX_CPUS}}$use_SWARM                    cpus: {{NODE_MAX_CPUS}}
}N}
{V:HAVE_VOLUMES{
volumes:{{HAVE_VOLUMES}}
}V}
{W:VOLUME_NAME{
{{VOLUME_COMMENT/shcom-}}
    {{VOLUME_NAME}}:
        driver_opts:
            type: none
            o: bind
            device: ${{{VOLUME_NAME/upper}}}
}W}
