apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{NAME}}-{{MAIN_POD}}
  labels:
    app: {{NAME}}
    flow-group: {{NAME}}
spec:
  replicas: ${replicas_{{NAME/id/upper}}}
  selector:
    matchLabels:
      app: {{NAME}}
  template:
    metadata:
      labels:
        app: {{NAME}}
        flow-group: {{NAME}}
    spec:
{X:HAVE_IMAGE_PULL_SECRETS{
      imagePullSecrets:{{HAVE_IMAGE_PULL_SECRETS}}}X}
{S:IMAGE_PULL_SECRET{
      - name: "{{IMAGE_PULL_SECRET}}"
}S}
      containers:
      - name: {{NAME}}
        image: "{{PUSH_REPO-}}{{IMAGE}}"
        command: ["/home/worker/{{NAME}}/{{NAME}}-server"]
        args: ["{{MAIN_PORT}}"]
        ports:
          - name: grpc
            containerPort: {{MAIN_PORT}}
          - name: rest
            containerPort: {{REST_PORT}}
        env:
          - name: {{NAME/id/upper}}_REST_PORT
            value: "{{REST_PORT}}"
          - name: {{NAME/id/upper}}_ASYNC
            value: "1"
{K:MAIN_ENVIRONMENT_KEY{
          - name: {{MAIN_ENVIRONMENT_KEY}}
            value: "{{MAIN_ENVIRONMENT_VALUE}}"
}K}
$enable_htdocs        volumeMounts:
$enable_htdocs        - name: {{HTDOCS_VOLUME_NAME}}
$enable_htdocs          mountPath: "/home/worker/pr/htdocs"
$enable_htdocs          readOnly: true

{N:NODE_NAME{
{{EXTERN_NODE}}      - name: {{NODE_NAME/id/option}}
{{EXTERN_NODE}}        image: "$image_{{NODE_NAME/id/upper}}"
{{EXTERN_NODE}}        {{NODE_ENVIRONMENT}}
{{EXTERN_NODE}}        {{NODE_MOUNTS}}
{{EXTERN_NODE}}{{NODE_HAVE_MIN_MAX}}        resources:
{{EXTERN_NODE}}{{NODE_HAVE_MIN}}          requests:
{{EXTERN_NODE}}{{NODE_HAVE_MIN_MEMORY}}            memory: "{{NODE_MIN_MEMORY}}"
{{EXTERN_NODE}}{{NODE_HAVE_MIN_CPUS}}            cpu: "{{NODE_MIN_CPUS}}"
{{EXTERN_NODE}}{{NODE_HAVE_MIN_GPUS}}            nvidia.com/gpu: "{{NODE_MIN_GPUS}}"
{{EXTERN_NODE}}{{NODE_HAVE_MAX}}          limis:
{{EXTERN_NODE}}{{NODE_HAVE_MAX_MEMORY}}            memory: "{{NODE_MAX_MEMORY}}"
{{EXTERN_NODE}}{{NODE_HAVE_MAX_CPUS}}            cpu: "{{NODE_MAX_CPUS}}"
{{EXTERN_NODE}}{{NODE_HAVE_MAX_GPUS}}            nvidia.com/gpu: "{{NODE_MAX_GPUS}}"
}N}

$enable_htdocs      volumes:
$enable_htdocs$htdocs_PVC        - name: {{HTDOCS_VOLUME_NAME}}    
$enable_htdocs$htdocs_PVC          persistentVolumeClaim:
$enable_htdocs$htdocs_PVC            claimName: ${{{NAME/id/upper}}_HTDOCS}
$enable_htdocs$htdocs_COS        - name: cos-access-{{HTDOCS_VOLUME_NAME}}
$enable_htdocs$htdocs_COS          secret:
$enable_htdocs$htdocs_COS            secretName: ${{{NAME/id/upper}}_HTDOCS_SECRET_NAME}
$enable_htdocs$htdocs_ART        - name: api-key-{{HTDOCS_VOLUME_NAME}}
$enable_htdocs$htdocs_ART          secret:
$enable_htdocs$htdocs_ART            secretName: ${{{NAME/id/upper}}_HTDOCS_SECRET_NAME}
$enable_htdocs$htdocs_COS        - name: scratch-{{HTDOCS_VOLUME_NAME}}
$enable_htdocs$htdocs_COS          emptyDir: {}
$enable_htdocs$htdocs_ART        - name: scratch-{{HTDOCS_VOLUME_NAME}}
$enable_htdocs$htdocs_ART          emptyDir: {}

{W:VOLUME_NAME{
${{{VOLUME_NAME/id/upper}}_PVC}        - name: {{VOLUME_NAME/option}}
${{{VOLUME_NAME/id/upper}}_PVC}          persistentVolumeClaim:
${{{VOLUME_NAME/id/upper}}_PVC}            claimName: ${{{VOLUME_NAME/id/upper}}}
${{{VOLUME_NAME/id/upper}}_COS}        - name: cos-access-{{VOLUME_NAME/option}}
${{{VOLUME_NAME/id/upper}}_COS}          secret:
${{{VOLUME_NAME/id/upper}}_COS}            secretName: ${{{VOLUME_NAME/id/upper}}_SECRET_NAME}
${{{VOLUME_NAME/id/upper}}_ART}        - name: api-key-{{VOLUME_NAME/option}}
${{{VOLUME_NAME/id/upper}}_ART}          secret:
${{{VOLUME_NAME/id/upper}}_ART}            secretName: ${{{VOLUME_NAME/id/upper}}_SECRET_NAME}
${{{VOLUME_NAME/id/upper}}_COS}        - name: scratch-{{VOLUME_NAME/option}}
${{{VOLUME_NAME/id/upper}}_COS}          emptyDir: {}
${{{VOLUME_NAME/id/upper}}_ART}        - name: scratch-{{VOLUME_NAME/option}}
${{{VOLUME_NAME/id/upper}}_ART}          emptyDir: {}
}W}
---
apiVersion: v1
kind: Service
metadata:
  name: {{NAME}}
  labels:
    flow-group: {{NAME}}
    app: {{NAME}}
spec:
  ports:
  - port: {{MAIN_PORT}}
    protocol: TCP
    name: grpc
  - port:  {{REST_PORT}}
    protocol: TCP
    name: http
  selector:
    app: {{NAME}}
